const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
require.extensions['.ts']=(module,filename)=>module._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,filename);
global.document={createElement:()=>({width:0,height:0,getContext:()=>new Proxy({measureText:text=>({width:text.length*25})},{get:(object,key)=>object[key]??(()=>{}),set:(object,key,value)=>(object[key]=value,true)})})};
const T=require('three'),kit=require('../app/architecture-kit'),{disposeScene}=require('../app/scene-resources');
test.before(async()=>{const {GLTFLoader}=require('three/addons/loaders/GLTFLoader.js'),bytes=fs.readFileSync(path.resolve(__dirname,'../public/assets/architecture-kit.glb')),asset=(await new GLTFLoader().parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'')).scene;assert.equal(kit.installArchitectureKit(asset),true);disposeScene(asset);const worldBytes=fs.readFileSync(path.resolve(__dirname,'../public/assets/kingdom-world-kit.glb')),worldAsset=(await new GLTFLoader().parseAsync(worldBytes.buffer.slice(worldBytes.byteOffset,worldBytes.byteOffset+worldBytes.byteLength),'')).scene;assert.equal(require('../app/world-kit').installWorldKit(worldAsset),true);disposeScene(worldAsset);kit.installArchitectureSurfaces(Object.fromEntries(['ceramic','stone','timber','brushed'].map(kind=>[kind,new T.DataTexture(new Uint8Array([128,240,255,255]),1,1)])))});

test('Blender structural modules preserve requested bounds and bounded edge radii',()=>{
 for(const [width,height,depth,radius] of [[4,9,3,.12],[.06,5,.08,0],[28,.2,16,.025]]){const geometry=kit.authoredBlock(width,height,depth,radius),size=geometry.boundingBox.getSize(new T.Vector3());assert.ok(Math.abs(size.x-width)<.00001&&Math.abs(size.y-height)<.00001&&Math.abs(size.z-depth)<.00001);assert.ok(geometry.userData.authoredArchitecture);assert.ok((geometry.index?.count??geometry.attributes.position.count)/3<=60);geometry.dispose()}
});
test('fitted block templates use bounded LRU reuse without sharing mutable vertex buffers',context=>{
 const probe=kit.authoredBlock(.321,.432,.543,.012),prototype=Object.getPrototypeOf(probe),normals=prototype.computeVertexNormals;probe.dispose();let fitted=0;context.mock.method(prototype,'computeVertexNormals',function(){fitted++;return normals.call(this)});
 const first=kit.authoredBlock(2.345,1.234,3.456,.09),before=fitted,second=kit.authoredBlock(2.345,1.234,3.456,.09);assert.ok(before>0);assert.equal(fitted,before);assert.notEqual(first.attributes.position.array.buffer,second.attributes.position.array.buffer);assert.deepEqual(first.attributes.normal.array,second.attributes.normal.array);assert.deepEqual(first.attributes.uv.array,second.attributes.uv.array);assert.deepEqual(second.parameters,{width:2.345,height:1.234,depth:3.456,radius:.09});first.attributes.position.setX(0,900);assert.notEqual(second.attributes.position.getX(0),900);first.dispose();
 for(let index=0;index<130;index++)kit.authoredBlock(3.1+index,.7,.8,.05).dispose();const evicted=fitted,third=kit.authoredBlock(2.345,1.234,3.456,.09);assert.equal(fitted,evicted+1);assert.deepEqual(third.attributes.position.array,second.attributes.position.array);second.dispose();third.dispose();
});
test('all architecture families use authored structures without losing their recipe or facade parts',()=>{
 const {createCraftedBuilding,bakeArchitecture}=require('../app/building-craft'),{architectureProfiles}=require('../app/architecture-profiles');
 for(const style of Object.keys(architectureProfiles)){const building=createCraftedBuilding({style,address:'blender/'+style});assert.equal(building.root.userData.authoredArchitecture,true);assert.ok(building.root.getObjectByName('Residence_StructuralStorey').geometry.userData.authoredArchitecture);assert.ok(building.root.getObjectByName('Residence_DoorLeaf'));const skins=bakeArchitecture(building.root);assert.ok(skins.every(skin=>skin.geometry?.attributes.position));for(const skin of skins){skin.geometry.dispose();skin.material.dispose()}}
});
test('Blender conversion does not seal an open pipe or replace textured display geometry',()=>{
 const pipe=new T.Mesh(new T.CylinderGeometry(1,1,2,16,1,true),new T.MeshStandardMaterial()),screen=new T.Mesh(new T.BoxGeometry(2,2,.1),new T.MeshStandardMaterial({map:new T.Texture()}));assert.equal(kit.applyAuthoredArchitecture(pipe),false);assert.equal(kit.applyAuthoredArchitecture(screen),false);disposeScene(pipe);disposeScene(screen);
});
test('mixed authored and procedural meshes sharing a material retain defined colors and instanced edges',()=>{
 const material=new T.MeshStandardMaterial(),root=new T.Group(),box=new T.InstancedMesh(new T.BoxGeometry(1,1,1),material,2),curve=new T.Mesh(new T.TorusGeometry(2,.05,4,16,Math.PI),material);root.add(box,curve);kit.completeArchitectureAttributes(root);assert.equal(box.geometry.userData.authoredArchitecture,'Architecture_PlainBlock');assert.ok(curve.geometry.attributes.color);assert.ok(curve.geometry.attributes.color.array.every(value=>value===1));disposeScene(root);
});
test('authored rings retain their bores and orientation and large cylinders retain smooth silhouettes',()=>{
 for(const rotation of [new T.Euler(),new T.Euler(Math.PI/2,0,0),new T.Euler(0,Math.PI/2,0)]){const shape=new T.TorusGeometry(1,.08,8,24).applyMatrix4(new T.Matrix4().makeRotationFromEuler(rotation)),mesh=new T.Mesh(shape,new T.MeshStandardMaterial()),normal=new T.Vector3(0,0,1).applyEuler(rotation);shape.computeBoundingBox();const before=shape.boundingBox.clone();assert.equal(kit.applyAuthoredArchitecture(mesh),true);mesh.updateMatrixWorld(true);assert.equal(new T.Raycaster(normal.clone().multiplyScalar(4),normal.clone().negate()).intersectObject(mesh).length,0);assert.ok(mesh.geometry.boundingBox.min.distanceTo(before.min)<.001);assert.ok(mesh.geometry.boundingBox.max.distanceTo(before.max)<.001);disposeScene(mesh)}
 const disk=new T.Mesh(new T.CylinderGeometry(28,28,.3,96),new T.MeshStandardMaterial());assert.equal(kit.applyAuthoredArchitecture(disk),true);assert.equal(disk.geometry.userData.authoredArchitecture,'Architecture_CylinderHigh');disposeScene(disk);
});
test('the city can bake the authored building modules without incompatible attributes',()=>{
 const {createCityExpansion}=require('../app/city-expansion'),scene=new T.Scene(),errors=[],original=console.error;console.error=(...values)=>errors.push(values.join(' '));let city;try{city=createCityExpansion(scene);scene.traverse(object=>{if(object.isMesh)assert.ok(object.geometry?.attributes.position)});assert.deepEqual(errors,[])}finally{console.error=original;city?.dispose();disposeScene(scene)}
});
test('authored facade materials retain distinct surface bakes and the pavilion keeps its clear approach',()=>{
 const {architectureMaterials}=require('../app/building-craft'),materials=architectureMaterials('atelier');assert.equal(materials.wall.bumpMap.userData.authoredSurface,'ceramic');assert.equal(materials.wood.bumpMap.userData.authoredSurface,'timber');assert.equal(materials.stone.bumpMap.userData.authoredSurface,'stone');assert.equal(materials.metal.bumpMap.userData.authoredSurface,'brushed');
 const {createCapitalPavilion}=require('../app/capital-pavilion'),{createCivicKit}=require('../app/civic-kit'),scene=new T.Scene(),pavilion=createCapitalPavilion(scene,createCivicKit().materials),bounds=new T.Box3().setFromObject(pavilion.root);assert.ok(bounds.max.y>13.5&&bounds.max.y<14.5);for(let forward=159;forward<170;forward+=.25)for(const horizontal of [48,52,56])assert.ok(pavilion.solids.every(solid=>!solid.clone().expandByScalar(.4).containsPoint(new T.Vector3(horizontal,.8,forward))));disposeScene(scene);for(const material of Object.values(materials))material.dispose();
});
test('returned Blender normal maps preserve material colors and use independently disposable texture views',()=>{
 const kinds=['ceramic','stone','timber','brushed'],maps=Object.fromEntries(kinds.map(kind=>[kind,new T.Texture()])),normals=Object.fromEntries(kinds.map(kind=>[kind,new T.Texture()]));kit.installArchitectureSurfaces(maps,normals);const {architectureMaterials}=require('../app/building-craft'),first=architectureMaterials('atelier'),second=architectureMaterials('atelier');for(const key of ['wall','stone','wood','metal']){assert.ok(first[key].normalMap);assert.equal(first[key].normalMap.userData.blenderSceneFinish,'surface-normal-v1');assert.equal(first[key].normalMap.colorSpace,T.NoColorSpace);assert.notEqual(first[key].normalMap,second[key].normalMap);assert.equal(first[key].color.getHex(),second[key].color.getHex())}const {createCraftMaterials}=require('../app/crafted-surfaces'),paint=createCraftMaterials()('#aaccee');assert.ok(paint.normalMap);assert.equal(paint.color.getHexString(),'aaccee');for(const material of [...Object.values(first),...Object.values(second),paint])material.dispose();
});
test('the premium library keeps dense facial spheres separate from inexpensive background geometry',async()=>{
 const {GLTFLoader}=require('three/addons/loaders/GLTFLoader.js'),bytes=fs.readFileSync(path.resolve(__dirname,'../public/assets/premium-v1/architecture-kit.glb')),asset=(await new GLTFLoader().parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'')).scene;assert.equal(kit.installArchitectureKit(asset),true);disposeScene(asset);
 const original=new T.SphereGeometry(1,12,9),material=new T.MeshStandardMaterial(),face=new T.Mesh(original,material),background=new T.Mesh(original,material);face.name='navy face panel';background.name='Ground_Surface';assert.equal(kit.applyAuthoredArchitecture(face),true);assert.equal(kit.applyAuthoredArchitecture(background),true);assert.equal(face.geometry.userData.authoredArchitecture,'Architecture_DetailSphere');assert.equal(background.geometry.userData.authoredArchitecture,'Architecture_Sphere');assert.ok(face.geometry.attributes.position.count>background.geometry.attributes.position.count*3);const block=kit.authoredBlock(4,9,3,.12);assert.ok((block.index?.count??block.attributes.position.count)/3<=100);assert.deepEqual(block.boundingBox.getSize(new T.Vector3()).toArray(),[4,9,3]);block.dispose();disposeScene(face);disposeScene(background);
});
