const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
require.extensions['.ts']=(module,file)=>module._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,file);
const T=require('three'),{createExportSnapshot,exportSnapshot}=require('../app/complete-scene-export');
global.FileReader=class{readAsArrayBuffer(blob){blob.arrayBuffer().then(value=>{this.result=value;this.onloadend?.()}).catch(error=>this.onerror?.(error))}};

test('complete snapshots preserve instance transforms, colors, hidden objects and material groups without mutating sources',async()=>{
 const root=new T.Group();root.scale.setScalar(2);root.name='World';const material=new T.MeshStandardMaterial({color:'#ffffff'}),geometry=new T.BoxGeometry(),instanced=new T.InstancedMesh(geometry,material,2);instanced.name='Trees';instanced.setMatrixAt(0,new T.Matrix4().makeTranslation(2,0,0));instanced.setMatrixAt(1,new T.Matrix4().makeTranslation(4,0,0));instanced.setColorAt(0,new T.Color('#ff0000'));instanced.setColorAt(1,new T.Color('#00ff00'));root.add(instanced);const hidden=new T.Mesh(geometry,[material,material,material,material,material,material]);hidden.name='Hidden';hidden.visible=false;root.add(hidden);
 const snapshot=createExportSnapshot([root],{zone:'test'}),trees=snapshot.scene.getObjectByName('Trees');assert.equal(trees.children.length,2);assert.equal(trees.children[0].material.color.getHexString(),'ff0000');assert.equal(trees.children[1].material.color.getHexString(),'00ff00');assert.equal(trees.children[1].getWorldPosition(new T.Vector3()).x,8);assert.equal(snapshot.scene.getObjectByName('Hidden').geometry,trees.children[0].geometry);assert.equal(snapshot.scene.getObjectByName('Hidden').visible,true);assert.equal(hidden.visible,false);assert.equal(material.color.getHexString(),'ffffff');const bytes=await exportSnapshot(snapshot),buffer=Buffer.from(bytes),json=JSON.parse(buffer.subarray(20,20+buffer.readUInt32LE(12)).toString());assert.ok(!json.extensionsUsed?.includes('EXT_mesh_gpu_instancing'));assert.ok(json.meshes.some(mesh=>mesh.primitives.length===6));snapshot.dispose();assert.equal(root.children.length,2);geometry.dispose();material.dispose();
});
test('complete snapshots choose one LOD, preserve identities and record unsupported shaders',()=>{
 const root=new T.Group(),lod=new T.LOD(),high=new T.Mesh(new T.BoxGeometry(),new T.MeshStandardMaterial()),low=new T.Mesh(new T.BoxGeometry(),new T.MeshStandardMaterial());high.name='Full';low.name='Proxy';lod.addLevel(high,0);lod.addLevel(low,100);root.add(lod);const shader=new T.Mesh(new T.PlaneGeometry(),new T.ShaderMaterial({uniforms:{tint:{value:new T.Color('#559977')}}}));shader.name='Water';root.add(shader);const snapshot=createExportSnapshot([root],{zone:'test'});assert.ok(snapshot.scene.getObjectByName('Full'));assert.equal(snapshot.scene.getObjectByName('Proxy'),undefined);assert.equal(snapshot.manifest.shaders.length,1);assert.equal(snapshot.manifest.objects.find(record=>record.name==='Water').notes.length,1);assert.equal(new Set(snapshot.manifest.objects.map(record=>record.id)).size,snapshot.manifest.objects.length);snapshot.dispose();
});
test('export reconstruction restores every detailed building without changing live streaming state',()=>{
 const {createArchitectureNeighborhood,rebuildArchitectureForExport,releaseArchitectureGeometry}=require('../app/architecture-neighborhood'),root=new T.Group(),town=createArchitectureNeighborhood(root,'atelier',[{address:'export/one',position:new T.Vector3(3,0,2),rotation:new T.Quaternion(),width:4,height:7,depth:4}]);assert.equal(town.detailed,false);const exported=rebuildArchitectureForExport(town.root);assert.ok(exported.getObjectByName('Residence_DoorLeaf'));assert.deepEqual(exported.userData.buildingAddresses,['export/one']);assert.equal(town.detailed,false);releaseArchitectureGeometry(exported);town.dispose();
});
test('nested LOD selection and reconstructed roots retain world transforms',()=>{
 const world=new T.Group();world.position.set(12,3,-8);world.scale.setScalar(2);const lod=new T.LOD();lod.position.set(5,1,4);lod.rotation.y=.6;world.add(lod);const full=new T.Group();full.position.set(2,0,1);lod.addLevel(full,0);const mesh=new T.Mesh(new T.BoxGeometry(),new T.MeshStandardMaterial());mesh.name='Placed';mesh.position.set(3,4,5);full.add(mesh);world.updateMatrixWorld(true);const expected=mesh.getWorldPosition(new T.Vector3()),snapshot=createExportSnapshot([world],{zone:'lod'});assert.ok(snapshot.scene.getObjectByName('Placed').getWorldPosition(new T.Vector3()).distanceTo(expected)<1e-10);snapshot.dispose();
 const replacement=new T.Group();replacement.matrix.copy(full.matrix);replacement.matrixAutoUpdate=false;const child=new T.Mesh(mesh.geometry,mesh.material);child.name='Rebuilt';child.position.copy(mesh.position);replacement.add(child);const exported=createExportSnapshot([full],{zone:'replacement',replace:new Map([[full,replacement]])});assert.ok(exported.scene.getObjectByName('Rebuilt').getWorldPosition(new T.Vector3()).distanceTo(expected)<1e-10);exported.dispose();
});
test('finite draw ranges retain only rendered indices, vertices and material groups',()=>{
 const indexed=new T.BoxGeometry();indexed.setDrawRange(6,6);const nonindexed=indexed.toNonIndexed();nonindexed.setDrawRange(9,3);const material=new T.MeshStandardMaterial(),first=new T.Mesh(indexed,[material,material,material,material,material,material]),second=new T.Mesh(nonindexed,material);first.name='Indexed';second.name='Nonindexed';const snapshot=createExportSnapshot([first,second],{zone:'ranges'}),cut=snapshot.scene.getObjectByName('Indexed').geometry,vertices=snapshot.scene.getObjectByName('Nonindexed').geometry;assert.equal(cut.index.count,6);assert.deepEqual(cut.groups,[{start:0,count:6,materialIndex:1}]);assert.equal(vertices.attributes.position.count,3);assert.equal(vertices.attributes.position.getX(0),nonindexed.attributes.position.getX(9));assert.equal(indexed.index.count,36);snapshot.dispose();
});
test('skinned and morph snapshots bake the current pose without mutating source geometry',()=>{
 const geometry=new T.BoxGeometry(),count=geometry.attributes.position.count;geometry.setAttribute('skinIndex',new T.Uint16BufferAttribute(new Uint16Array(count*4),4));const weights=new Float32Array(count*4);for(let index=0;index<count;index++)weights[index*4]=1;geometry.setAttribute('skinWeight',new T.Float32BufferAttribute(weights,4));const mesh=new T.SkinnedMesh(geometry,new T.MeshStandardMaterial()),bone=new T.Bone();mesh.name='Rig';mesh.add(bone);mesh.bind(new T.Skeleton([bone]));bone.position.y=3;mesh.updateMatrixWorld(true);const originalY=geometry.attributes.position.getY(0),snapshot=createExportSnapshot([mesh],{zone:'pose'}),posed=snapshot.scene.getObjectByName('Rig');assert.equal(posed.geometry.attributes.position.getY(0),originalY+3);assert.equal(posed.geometry.attributes.skinIndex,undefined);assert.equal(geometry.attributes.position.getY(0),originalY);snapshot.dispose();
});
test('lossless GLB buffer reuse preserves every node, material, extension and attribute byte',async()=>{
 const {compactGlb,parseGlb,verifyEquivalent}=require('../scripts/complete-export-format.cjs'),first=new T.Mesh(new T.BoxGeometry(),new T.MeshPhysicalMaterial({clearcoat:.7})),second=new T.Mesh(new T.BoxGeometry(),first.material);first.name='First';second.name='Second';second.position.x=9;first.userData.identity='source/first';second.userData.identity='source/second';const snapshot=createExportSnapshot([first,second],{zone:'compact'}),original=Buffer.from(await exportSnapshot(snapshot)),compact=compactGlb(original);assert.ok(compact.length<original.length);verifyEquivalent(original,compact);assert.equal(parseGlb(compact).document.nodes.length,parseGlb(original).document.nodes.length);assert.equal(parseGlb(compact).document.nodes.filter(node=>node.name==='First'||node.name==='Second').length,2);assert.ok(parseGlb(compact).document.extensionsUsed.includes('KHR_materials_clearcoat'));snapshot.dispose();
});
test('complete city zones keep their entire resident population in the correct world-space block',async()=>{
 const {exportCompleteZone}=require('../app/complete-world-export'),scene=new T.Scene(),cityRoot=new T.Group(),lod=new T.LOD(),near=new T.Group();scene.scale.setScalar(2);scene.add(cityRoot);cityRoot.add(lod);lod.position.set(-450,0,-1121);lod.addLevel(near,0);const marker=new T.Mesh(new T.BoxGeometry(),new T.MeshStandardMaterial());near.add(marker);const world={scene,city:{root:cityRoot,neighborhoods:[lod],pedestrians:[{x:-485,z:-1121,phase:1,variant:0},{x:-415,z:-1121,phase:-1,variant:1}]}};const result=await exportCompleteZone(world,{id:'city-block-0',kind:'city-block',index:0});assert.equal(result.manifest.cityResidents,2);assert.ok(result.manifest.residentPositions.every(position=>position[0]<-800&&position[2]<-2100));
});
test('directional lights retain their actual target direction under world scaling',()=>{
 const root=new T.Group(),light=new T.DirectionalLight();root.scale.setScalar(2);light.name='Sun';light.position.set(5,10,2);light.target.position.set(-10,0,-4);root.add(light,light.target);root.updateMatrixWorld(true);const expected=light.target.getWorldPosition(new T.Vector3()).sub(light.getWorldPosition(new T.Vector3())).normalize(),snapshot=createExportSnapshot([root],{zone:'lighting'}),sun=snapshot.scene.getObjectByName('Sun'),actual=new T.Vector3(0,0,-1).applyQuaternion(sun.getWorldQuaternion(new T.Quaternion()));assert.ok(actual.dot(expected)>1-1e-10);assert.equal(sun.target.parent,sun);snapshot.dispose();
});
