const assert=require('node:assert/strict');const test=require('node:test');const fs=require('node:fs');const ts=require('typescript');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,f);
const {DeliveryRound,recipients}=require('../app/delivery-state.ts');
test('charging, pickup, and inventory conservation across a full round',()=>{const r=new DeliveryRound();assert(!r.collect());assert(r.prepare());assert(!r.prepare());r.tick(2.9);assert.equal(r.snapshot.stock,0);assert(!r.collect());r.tick(.2);assert.equal(r.snapshot.stock,4);for(let i=0;i<4;i++)assert(r.collect());assert(!r.collect());assert.equal(r.snapshot.inventory,4);for(const id of recipients){assert(r.deliver(id));assert.equal(r.snapshot.stock+r.snapshot.inventory+r.snapshot.delivered.length,4)}assert.equal(r.snapshot.phase,'complete');assert.equal(r.snapshot.completedRounds,1);assert.equal(r.snapshot.inventory,0)});
test('partial collection works and duplicate or invalid recipients cannot consume stock or reward twice',()=>{const r=new DeliveryRound();r.prepare();r.tick(3);r.collect();assert(r.deliver('owl'));const before=r.snapshot;assert(!r.deliver('owl'));assert(!r.deliver('gopher'));assert(!r.deliver('cloud'));assert.deepEqual(r.snapshot,before);r.collect();assert(r.deliver('cloud'));assert.equal(r.snapshot.stock,2)});
test('new rounds require completion and an explicit command, and preserve discoveries',()=>{const r=new DeliveryRound();r.discover('kiln','Compiler kiln');assert(!r.nextRound());r.prepare();r.tick(3);for(let i=0;i<4;i++)r.collect();for(const id of recipients)r.deliver(id);r.tick(100);assert.equal(r.snapshot.round,1);assert(!r.deliver('owl'));assert.equal(r.snapshot.completedRounds,1);assert(r.nextRound());assert.equal(r.snapshot.round,2);assert.deepEqual(r.snapshot.discoveries,['kiln']);assert.equal(r.snapshot.completedRounds,1);assert.deepEqual(r.snapshot.delivered,[]);assert(!r.discover('kiln','Compiler kiln'));assert(!r.nextRound())});

const {createCourier}=require('../app/courier.ts');
test('modeled capsule visibility matches inventory and facial parts remain addressable',()=>{const c=createCourier();for(let count=0;count<=4;count++){c.update(.016,count);assert.equal(c.parts.cargo.filter(part=>part.visible).length,count)}assert.equal(c.parts.leftEye.name,'left eye');assert.equal(c.parts.rightEye.name,'right eye');assert.equal(c.parts.smile.name,'smile');c.gesture('greeting');c.update(.1,2);assert(c.parts.rightArm.rotation.z<0)});
