const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
require.extensions['.ts']=(module,filename)=>module._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,filename);
const {parseDiagnosticBatch,sanitizeDiagnosticData,diagnosticLimits,diagnosticText}=require('../lib/diagnostics-schema.ts'),{POST}=require('../app/api/client-diagnostics/route.ts');
const event={type:'window_error',sessionId:'session-12345',pageId:'document-12345',seq:1,at:Date.now(),uptime:10,data:{message:'failed'}},batch={version:1,events:[event]};
function request(body=batch,headers={}){return new Request('https://kingdom.test/api/client-diagnostics',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://kingdom.test',...headers},body:typeof body==='string'?body:JSON.stringify(body)})}
test('diagnostics use an allowlist and remove credentials, query strings and arbitrary user content',()=>{
 assert.equal(diagnosticText('alpha\u0000beta\r\n\t\u007fend'),'alpha beta \n\t end');
 const clean=sanitizeDiagnosticData({resource:'https://user:pass@site.test/model.glb?token=private#secret',message:'token=private contact person@example.com https://site.test/api?password=secret',stack:'Error at https://site.test/app.js?token=secret:1',chat:'private chat',cookies:'private cookies',heapUsed:123,hidden:true,nested:{token:'secret'}});
 assert.equal(clean.resource,'https://site.test/model.glb');assert.ok(!JSON.stringify(clean).includes('private'));assert.ok(!JSON.stringify(clean).includes('person@example.com'));assert.equal(clean.chat,undefined);assert.equal(clean.cookies,undefined);assert.equal(clean.nested,undefined);assert.equal(clean.heapUsed,123);
 assert.equal(parseDiagnosticBatch({version:1,events:[{...event,type:'arbitrary_event'}]}),null);assert.equal(parseDiagnosticBatch({version:1,events:Array(diagnosticLimits.batchEvents+1).fill(event)}),null);
 assert.equal(parseDiagnosticBatch({version:1,events:[{...event,sessionId:undefined}]}),null);
});
test('ingestion emits one sanitized JSON line per event with correlation and no caching',async context=>{
 const records=[];context.mock.method(console,'warn',line=>records.push(JSON.parse(line)));const response=await POST(request());assert.equal(response.status,204);assert.equal(response.headers.get('Cache-Control'),'no-store');assert.equal(records.length,1);assert.equal(records[0].tag,'KINGDOM_CLIENT');assert.equal(records[0].sessionId,event.sessionId);assert.equal(records[0].pageId,event.pageId);assert.equal(records[0].source,'unverified-browser');assert.equal(records[0].data.message,'failed');
});
test('ingestion rejects cross-site posts, malformed or oversized data and rate-limits abuse',async context=>{
 context.mock.method(console,'warn',()=>{});assert.equal((await POST(request(batch,{Origin:'https://other.test'}))).status,403);assert.equal((await POST(request(batch,{'Content-Type':'text/plain'}))).status,415);assert.equal((await POST(request('{broken'))).status,400);assert.equal((await POST(request(' '.repeat(diagnosticLimits.batchBytes+1)))).status,413);
 let limited=false;for(let count=0;count<65;count++)if((await POST(request(batch,{'x-forwarded-for':'test-client'}))).status===429)limited=true;assert.equal(limited,true);
});

function browserFixture(context){
 const keys=['window','document','navigator','sessionStorage','location','innerWidth','innerHeight','devicePixelRatio','PerformanceObserver'],saved=new Map(keys.map(key=>[key,Object.getOwnPropertyDescriptor(global,key)])),view=new EventTarget(),document=new EventTarget(),storage=new Map(),requests=[],beacons=[];
 view.top=view;view.fetch=async(url,options)=>{requests.push({url,options});return new Response(null,{status:204})};document.hidden=false;document.querySelector=()=>null;
 const values={window:view,document,navigator:{onLine:true,userAgent:'iPhone OS 18_7 [LinkedInApp]',hardwareConcurrency:4,sendBeacon:(url,body)=>{beacons.push({url,body});return true}},sessionStorage:{getItem:key=>storage.get(key)??null,setItem:(key,value)=>storage.set(key,value)},location:new URL('https://kingdom.test/?token=secret'),innerWidth:390,innerHeight:844,devicePixelRatio:2,PerformanceObserver:{supportedEntryTypes:[]}};
 for(const [key,value] of Object.entries(values))Object.defineProperty(global,key,{configurable:true,value});context.after(()=>{for(const [key,descriptor] of saved)if(descriptor)Object.defineProperty(global,key,descriptor);else delete global[key]});return {view,document,storage,requests,beacons,values};
}
test('browser recorder batches safely, survives duplicate initialization, captures errors and restores hooks',async context=>{
 const fixture=browserFixture(context),original=fixture.view.fetch,{startClientDiagnostics,recordDiagnostic,exportDiagnostics}=require('../app/client-diagnostics.ts'),first=startClientDiagnostics(),second=startClientDiagnostics();
 try{await Promise.resolve();await Promise.resolve();assert.equal(fixture.requests.length,1);first();await Promise.resolve();const error=new Event('error');Object.assign(error,{message:'bad token=hidden',filename:'https://kingdom.test/app.js?secret=value',lineno:2,colno:4,error:new Error('bad token=hidden')});fixture.view.dispatchEvent(error);const report=JSON.parse(exportDiagnostics());assert.equal(report.events.filter(event=>event.type==='app_started').length,1);assert.equal(report.events.at(-1).type,'window_error');assert.ok(!JSON.stringify(report).includes('token=hidden'));second();await Promise.resolve();assert.equal(fixture.view.fetch,original);assert.ok(fixture.beacons.length>0);recordDiagnostic('window_error',{message:'after dispose'});assert.equal(JSON.parse(exportDiagnostics()).events.length,0)}finally{first();second();await Promise.resolve()}
});
test('offline history and pending delivery stay bounded and replay uses the same session with a new page',async context=>{
 const fixture=browserFixture(context),{startClientDiagnostics,recordDiagnostic,exportDiagnostics}=require('../app/client-diagnostics.ts');fixture.values.navigator.onLine=false;let stop=startClientDiagnostics();
 try{for(let count=0;count<300;count++)recordDiagnostic('asset_ready',{resource:'/assets/'+count+'.glb',bytes:count});const first=JSON.parse(exportDiagnostics());assert.ok(first.events.length<=diagnosticLimits.history);assert.ok(first.pending<=diagnosticLimits.queue);assert.ok(first.dropped>0);fixture.view.dispatchEvent(new Event('pagehide'));assert.equal(fixture.requests.length,0);stop();await Promise.resolve();stop=startClientDiagnostics();const second=JSON.parse(exportDiagnostics());assert.equal(second.sessionId,first.sessionId);assert.notEqual(second.pageId,first.pageId);assert.ok(second.events.some(event=>event.pageId===first.pageId));assert.equal(second.events.filter(event=>event.type==='previous_session_incomplete').length,0)}finally{stop();await Promise.resolve()}
});

test('delivery failures back off without recursion and later retries preserve correlation',async context=>{
 const fixture=browserFixture(context),{startClientDiagnostics,recordDiagnostic,exportDiagnostics}=require('../app/client-diagnostics.ts');let now=Date.now(),interval,attempt=0;
 context.mock.method(Date,'now',()=>now);context.mock.method(global,'setInterval',callback=>{interval=callback;return 1});context.mock.method(global,'clearInterval',()=>{});
 fixture.view.fetch=async(url,options)=>{fixture.requests.push({url,options});if(++attempt<3)throw Error('diagnostic transport unavailable');return new Response(null,{status:204})};const stop=startClientDiagnostics();
 try{await Promise.resolve();await Promise.resolve();assert.equal(attempt,1);assert.equal(JSON.parse(exportDiagnostics()).deliveryFailures,1);recordDiagnostic('window_error',{message:'visible failure'});now+=10000;interval();await Promise.resolve();assert.equal(attempt,1);now+=10000;interval();await Promise.resolve();await Promise.resolve();assert.equal(attempt,2);now+=30000;interval();await Promise.resolve();assert.equal(attempt,2);now+=10000;interval();await Promise.resolve();await Promise.resolve();assert.equal(attempt,3);const report=JSON.parse(exportDiagnostics());assert.equal(report.deliveryFailures,0);assert.equal(report.pending,0);assert.equal(report.events.some(event=>event.type==='fetch_failed'),false);assert.equal(JSON.parse(fixture.requests[2].options.body).events[0].type,'window_error');assert.ok(fixture.requests.every(request=>Buffer.byteLength(request.options.body)<=diagnosticLimits.batchBytes))}finally{stop();await Promise.resolve()}
});

test('storage has a total byte cap, critical events survive bursts, and stale sends cannot overwrite a new page',async context=>{
 const fixture=browserFixture(context),{startClientDiagnostics,recordDiagnostic,exportDiagnostics}=require('../app/client-diagnostics.ts');let finish;fixture.view.fetch=()=>new Promise(resolve=>{finish=resolve});let stop=startClientDiagnostics();
 try{for(let count=0;count<150;count++)recordDiagnostic('asset_ready',{resource:'/assets/'+count,message:'m'.repeat(350)+count,stack:'s'.repeat(1800),scene:'scene'.repeat(40),phase:'phase'.repeat(32)});recordDiagnostic('window_error',{message:'critical sentinel'});fixture.view.dispatchEvent(new Event('pagehide'));let report=JSON.parse(exportDiagnostics());assert.equal(report.events.length,101);assert.equal(report.events.at(-1).type,'window_error');assert.ok(report.events.some(event=>event.data.message==='critical sentinel'));assert.ok(Buffer.byteLength(fixture.storage.get('kingdom-diagnostics:v1'))<=180000);const delivered=JSON.parse(await fixture.beacons[0].body.text());assert.equal(delivered.events[0].type,'window_error');stop();await Promise.resolve();fixture.values.navigator.onLine=false;stop=startClientDiagnostics();report=JSON.parse(exportDiagnostics());fixture.view.dispatchEvent(new Event('pagehide'));finish(new Response(null,{status:204}));await Promise.resolve();await Promise.resolve();assert.equal(JSON.parse(fixture.storage.get('kingdom-diagnostics:v1')).pageId,report.pageId)}finally{stop();await Promise.resolve()}
});

test('malformed storage and a failing context provider do not alter application fetch results',async context=>{
 const fixture=browserFixture(context),{startClientDiagnostics,setDiagnosticContext,exportDiagnostics}=require('../app/client-diagnostics.ts');fixture.storage.set('kingdom-diagnostics:v1','{not json');let fail=false;const expected=new Error('network failure');fixture.view.fetch=async url=>{if(String(url).endsWith('/application')){if(fail)throw expected;return new Response('ok')}return new Response(null,{status:204})};const stop=startClientDiagnostics();
 try{setDiagnosticContext(()=>{throw Error('bad provider')});assert.equal(await (await fixture.view.fetch('/application')).text(),'ok');fail=true;await assert.rejects(fixture.view.fetch('/application'),error=>error===expected);const report=JSON.parse(exportDiagnostics());assert.equal(report.events.at(-1).type,'fetch_failed');assert.equal(report.events.find(event=>event.type==='app_started').data.os,'ios 18.7')}finally{stop();await Promise.resolve()}
});

test('multiplayer state diagnostics omit room names, messages and identities',async context=>{
 const fixture=browserFixture(context),{startClientDiagnostics,exportDiagnostics}=require('../app/client-diagnostics.ts'),{FriendsClient}=require('../app/friends-client.ts'),saved=Object.getOwnPropertyDescriptor(global,'WebSocket');let socket;
 fixture.values.location.protocol='http:';fixture.values.location.hostname='127.0.0.1';Object.defineProperty(global,'WebSocket',{configurable:true,value:class{static OPEN=1;constructor(){socket=this;this.readyState=1;this.bufferedAmount=0}send(){}close(){}}});const stop=startClientDiagnostics(),client=new FriendsClient();
 try{client.join('create','PRIVATE_VISITOR');socket.onopen();socket.onclose({code:1006});socket.onmessage({data:JSON.stringify({type:'error',message:'PRIVATE_ROOM_AND_TOKEN'})});const report=JSON.parse(exportDiagnostics());assert.ok(report.events.some(event=>event.type==='service_state'&&event.data.action==='socket-closed'&&event.data.status===1006));assert.ok(report.events.some(event=>event.type==='service_failed'&&event.data.phase==='multiplayer'));assert.equal(JSON.stringify(report).includes('PRIVATE_'),false)}finally{client.dispose();stop();await Promise.resolve();if(saved)Object.defineProperty(global,'WebSocket',saved);else delete global.WebSocket}
});

test('browser identification uses the host app version rather than an earlier engine token',()=>{
 const {diagnosticBrowser}=require('../app/client-diagnostics.ts');assert.equal(diagnosticBrowser('Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit/605.1.15 Version/18.7 Mobile/15E148 Safari/604.1 [LinkedInApp]/9.32.4494'),'linkedin 9.32.4494');assert.equal(diagnosticBrowser('Chrome/140.0.0.0 Safari/537.36 Edg/139.0.1.2'),'edge 139.0.1.2');assert.equal(diagnosticBrowser('Version/18.7 Mobile/15E148 Safari/604.1'),'safari 18.7');assert.equal(diagnosticBrowser('CriOS/140.0.1.2 Mobile/15E148 Safari/604.1'),'chrome 140.0.1.2');
});

test('shader warnings remain warnings rather than being counted as runtime crashes',async context=>{
 const fixture=browserFixture(context),{startClientDiagnostics,exportDiagnostics}=require('../app/client-diagnostics.ts');fixture.values.navigator.onLine=false;context.mock.method(console,'warn',function(){assert.equal(this,console)});const stop=startClientDiagnostics();
 try{console.warn('THREE.WebGLProgram: Program Info Log: precision warning');console.warn('Handled optional failure',new Error('Handled failure'));const report=JSON.parse(exportDiagnostics());assert.equal(report.events.at(-2).type,'shader_warning');assert.equal(report.events.at(-1).type,'console_warning');assert.equal(report.events.some(event=>event.type==='window_error'||event.type==='shader_error'),false)}finally{stop();await Promise.resolve()}
});
