const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
require.extensions['.ts']=(module,filename)=>module._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,filename);
global.document={createElement:()=>({width:0,height:0,getContext:()=>new Proxy({measureText:text=>({width:text.length*25})},{get:(object,key)=>object[key]??(()=>{}),set:(object,key,value)=>(object[key]=value,true)})})};
const T=require('three'),{transitStops}=require('../app/transit-config.ts'),{createPlanetSurface,planetPoint,planetUp,planetGeography}=require('../app/planet-geography.ts'),{createPlanetInfrastructure}=require('../app/planet-infrastructure.ts'),{createPlanetPublicSpaces}=require('../app/planet-public-spaces.ts'),{createPlanetCanopy}=require('../app/planet-canopy.ts'),{disposeScene}=require('../app/scene-resources.ts');
test('every satellite has reference-style trees and banyans while keeping roads, public spaces and outposts clear',()=>{
 for(const stop of transitStops.slice(1)){
  const scene=new T.Scene(),surface=createPlanetSurface(stop,stop.radius),infrastructure=createPlanetInfrastructure(scene,surface),spaces=createPlanetPublicSpaces(scene,surface,infrastructure),outposts=Array.from({length:5},(_,index)=>({position:planetPoint(surface,index===4?new T.Vector3(0,-1,0):new T.Vector3(Math.cos(index*Math.PI*2/5),-.1,Math.sin(index*Math.PI*2/5)))})),trees=createPlanetCanopy(scene,surface,infrastructure,spaces.places,outposts);
  assert.ok(trees.records.length>=35,stop.id+' has '+trees.records.length+' trees');assert.equal(trees.banyans.length,2,stop.id+' needs a banyan in each hemisphere');assert.ok(trees.records.some(record=>record.direction.y>.3));assert.ok(trees.records.some(record=>record.direction.y<-.6));
  for(const record of trees.records){const land=planetGeography(surface,record.direction);assert.equal(land.water,false);assert.ok(land.road>=record.canopyRadius+3.8);assert.ok(land.river>=record.canopyRadius+3);assert.ok(new T.Vector3(0,1,0).applyQuaternion(record.rotation).dot(planetUp(surface,record.position))>.999);assert.ok(outposts.every(outpost=>outpost.position.distanceTo(record.position)>record.canopyRadius+5.9));assert.ok(spaces.places.every(place=>place.position.distanceTo(record.position)>place.radius+record.canopyRadius+1.9));assert.equal(trees.blocked(record.position),true)}
  for(const place of spaces.places)assert.equal(trees.blocked(place.approach),false);for(const column of trees.columns){const ground=planetPoint(surface,column.position.clone().sub(surface.center));assert.ok(column.position.distanceTo(ground)<.1,'tree roots must meet terrain')}
  console.log(stop.name+': '+trees.records.length+' trees, '+trees.banyans.length+' banyans');disposeScene(scene);
 }
});
