const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
require.extensions['.ts']=(module,filename)=>module._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,filename);
global.document={createElement:()=>({width:0,height:0,getContext:()=>new Proxy({measureText:text=>({width:text.length*25})},{get:(object,key)=>object[key]??(()=>{}),set:(object,key,value)=>(object[key]=value,true)})})};
const T=require('three'),{transitStops}=require('../app/transit-config.ts'),{createPlanetSurface,planetPoint,planetUp,planetGeography}=require('../app/planet-geography.ts'),{createPlanetInfrastructure}=require('../app/planet-infrastructure.ts'),{createPlanetPublicSpaces}=require('../app/planet-public-spaces.ts'),{createPlanetCanopy}=require('../app/planet-canopy.ts'),{disposeScene}=require('../app/scene-resources.ts');
test('planet meadows follow both hemispheres, preserve terrain clearances and keep fixed buffers',()=>{
 const {createPlanetMeadow}=require('../app/planet-canopy.ts');
 for(const stop of transitStops.slice(1)){
  const surface=createPlanetSurface(stop,stop.radius),reserved=planetPoint(surface,new T.Vector3(.61,-.62,.49)),meadow=createPlanetMeadow(surface,[{position:reserved,radius:8}]),buffers=meadow.patches.map(patch=>patch.near.instanceMatrix.array);
  let planted=0;
  for(const direction of [new T.Vector3(.61,.62,.49),new T.Vector3(.61,-.62,.49),new T.Vector3(-.52,-.7,-.49)]){
   const observer=planetPoint(surface,direction);meadow.update(.016,false,observer);assert.ok(meadow.placements.length<=meadow.capacity);planted+=meadow.placements.length;
   for(const record of meadow.placements){const normal=record.position.clone().sub(surface.center).normalize(),land=planetGeography(surface,normal);assert.equal(land.water,false);assert.ok(land.road>=4.68);assert.ok(land.river>=3.78);assert.ok(record.position.distanceTo(planetPoint(surface,normal))<.06);assert.ok(new T.Vector3(0,1,0).applyQuaternion(record.rotation).dot(planetUp(surface,record.position))>.999);assert.ok(record.position.distanceTo(reserved)>8.7)}
   meadow.patches.forEach((patch,index)=>assert.equal(patch.near.instanceMatrix.array,buffers[index]));
  }
  assert.ok(planted>100,stop.id+' has no meadow ground cover');meadow.update(.1,true,reserved,false);assert.equal(meadow.root.visible,false);disposeScene(meadow.root);
 }
});
test('every satellite has reference-style trees and banyans while keeping roads, public spaces and outposts clear',()=>{
 for(const stop of transitStops.slice(1)){
  const scene=new T.Scene(),surface=createPlanetSurface(stop,stop.radius),infrastructure=createPlanetInfrastructure(scene,surface),spaces=createPlanetPublicSpaces(scene,surface,infrastructure),outposts=Array.from({length:5},(_,index)=>({position:planetPoint(surface,index===4?new T.Vector3(0,-1,0):new T.Vector3(Math.cos(index*Math.PI*2/5),-.1,Math.sin(index*Math.PI*2/5)))})),trees=createPlanetCanopy(scene,surface,infrastructure,spaces.places,outposts);
  assert.ok(trees.records.length>=35,stop.id+' has '+trees.records.length+' trees');assert.equal(trees.banyans.length,2,stop.id+' needs a banyan in each hemisphere');assert.ok(trees.records.some(record=>record.direction.y>.3));assert.ok(trees.records.some(record=>record.direction.y<-.6));
  for(const record of trees.records){const land=planetGeography(surface,record.direction);assert.equal(land.water,false);assert.ok(land.road>=record.canopyRadius+3.8);assert.ok(land.river>=record.canopyRadius+3);assert.ok(new T.Vector3(0,1,0).applyQuaternion(record.rotation).dot(planetUp(surface,record.position))>.999);assert.ok(outposts.every(outpost=>outpost.position.distanceTo(record.position)>record.canopyRadius+5.9));assert.ok(spaces.places.every(place=>place.position.distanceTo(record.position)>place.radius+record.canopyRadius+1.9));assert.equal(trees.blocked(record.position),true)}
  for(const place of spaces.places)assert.equal(trees.blocked(place.approach),false);for(const column of trees.columns){const ground=planetPoint(surface,column.position.clone().sub(surface.center));assert.ok(column.position.distanceTo(ground)<.1,'tree roots must meet terrain')}
    assert.ok(trees.gardens.length>=12&&trees.gardens.length<=32,stop.id+' has '+trees.gardens.length+' garden patches');const turfMaterials=new Set();let gardenTriangles=0;
    for(const garden of trees.gardens){const direction=garden.position.clone().sub(surface.center).normalize(),land=planetGeography(surface,direction);assert.equal(land.water,false);assert.ok(land.road>=garden.radius+2);assert.ok(land.river>=garden.radius+1.5);assert.ok(spaces.places.every(place=>place.approach.distanceTo(garden.position)>garden.radius+4));const lawn=garden.root.getObjectByName('Garden_TexturedTurf');turfMaterials.add(lawn.material);const vertices=lawn.geometry.attributes.position;for(let index=0;index<vertices.count;index+=4){const point=new T.Vector3().fromBufferAttribute(vertices,index).applyQuaternion(garden.rotation).add(garden.position),ground=planetPoint(surface,point.clone().sub(surface.center));assert.ok(point.distanceTo(ground)<.18,'garden turf must follow the terrain')}garden.root.traverse(object=>{assert.ok(!object.isLight);if(object.isMesh)gardenTriangles+=(object.geometry.index?.count??object.geometry.attributes.position.count)/3*(object.isInstancedMesh?object.count:1)})}
    assert.equal(turfMaterials.size,1);assert.ok(gardenTriangles<75000);assert.equal(trees.lawnAprons.length,spaces.places.length);assert.equal(new Set(trees.lawnAprons.map(apron=>apron.root.material)).size,1);
    for(const apron of trees.lawnAprons){const vertices=apron.root.geometry.attributes.position,indices=apron.root.geometry.index;assert.ok(indices.count>0);for(let index=0;index<indices.count;index+=7){const point=new T.Vector3().fromBufferAttribute(vertices,indices.getX(index)),direction=point.clone().sub(surface.center).normalize(),land=planetGeography(surface,direction);assert.equal(land.water,false);assert.ok(land.road>1.39,stop.id+' road clearance '+land.road);assert.ok(point.distanceTo(planetPoint(surface,direction))<.05)}}
    trees.update(0,true,trees.gardens[0].position,false);assert.equal(trees.groundcover.visible,false);trees.update(0,true,trees.gardens[0].position,true);assert.equal(trees.gardens[0].root.visible,true);
    console.log(stop.name+': '+trees.records.length+' trees, '+trees.banyans.length+' banyans, '+trees.gardens.length+' garden patches');disposeScene(scene);
 }
});
