const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
require.extensions['.ts']=(module,filename)=>module._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,filename);
global.document={createElement:()=>({width:0,height:0,getContext:()=>new Proxy({measureText:text=>({width:text.length*14})},{get:(object,key)=>object[key]??(()=>{}),set:(object,key,value)=>(object[key]=value,true)})})};
const T=require('three'),{createProjectInstallations}=require('../app/project-installations.ts'),{capitalProjects}=require('../app/project-studies.ts'),{createCivicKit}=require('../app/civic-kit.ts'),{disposeScene}=require('../app/scene-resources.ts');
test('six existing project names have distinct bounded local studies with retained source provenance',()=>{
 const scene=new T.Scene(),player=new T.Group(),studies=createProjectInstallations(scene,player,createCivicKit().materials);assert.deepEqual(studies.entries.map(entry=>entry.project.name),capitalProjects);assert.equal(new Set(studies.entries.map(entry=>entry.project.description)).size,6);let triangles=0,meshes=0;
 studies.root.traverse(object=>{assert.ok(!object.isLight);if(object.isMesh){meshes++;triangles+=(object.geometry.index?.count??object.geometry.attributes.position.count)/3*(object.isInstancedMesh?object.count:1)}});assert.ok(triangles<5000);assert.ok(meshes<45);
 for(const entry of studies.entries){assert.match(entry.project.scenario.simplification,/not this project's implementation/);player.position.set(entry.project.building.x,.8,entry.project.building.z+1.65);assert.match(studies.prompt(),/Run study/);assert.ok(studies.solids.every(bound=>!bound.clone().expandByScalar(.35).containsPoint(player.position)));assert.ok(studies.interact());for(let frame=0;frame<100;frame++)studies.update(.1,false,true);assert.equal(entry.state.snapshot.running,false);assert.equal(entry.state.snapshot.step,3);assert.ok(entry.token.visible)}disposeScene(scene);
});
test('study pause, off-world sleep and reduced-motion poses preserve state and display resources',()=>{
 const scene=new T.Scene(),player=new T.Group(),studies=createProjectInstallations(scene,player,createCivicKit().materials),entry=studies.entries[0];player.position.set(33,.8,153.65);studies.interact();studies.update(.1,false,true);const before=entry.state.snapshot,position=entry.token.position.clone();studies.update(20,false,false);assert.equal(entry.state.snapshot,before);assert.ok(entry.token.position.equals(position));studies.interact();assert.equal(entry.state.snapshot.paused,true);for(let frame=0;frame<30;frame++)studies.update(.1,false,true);assert.equal(entry.state.snapshot.step,0);studies.interact();assert.equal(entry.state.snapshot.paused,false);studies.update(0,true,true);const reduced=entry.token.position.clone();studies.update(.1,true,true);assert.ok(entry.token.position.equals(reduced));const texture=entry.group.getObjectByName('Study_Readout').material.map;for(let frame=0;frame<80;frame++)studies.update(.1,true,true);assert.equal(entry.group.getObjectByName('Study_Readout').material.map,texture);disposeScene(scene);
});
test('selection exposes the existing sequencer and releases controls when leaving the installation',()=>{
 const scene=new T.Scene(),player=new T.Group(),changes=[],studies=createProjectInstallations(scene,player,createCivicKit().materials,study=>changes.push(study));player.position.set(33,.8,153.65);studies.interact();assert.equal(studies.selected,studies.entries[0].state);assert.equal(changes.length,1);studies.interact();assert.equal(changes.length,1);player.position.set(52,.8,201);studies.update(.1,false,true);assert.equal(studies.selected,null);assert.deepEqual(changes,[studies.entries[0].state,null]);studies.dismiss();assert.equal(changes.length,2);disposeScene(scene);
});
test('inspection cameras frame every study with unobstructed pavilion sight lines in the doubled world',()=>{
 const {studyCameraView}=require('../app/project-installations.ts'),{createCapitalWorld}=require('../app/capital-world.ts'),{createGameCamera}=require('../app/game-camera.ts'),{defaultSettings}=require('../app/persistence.ts'),scene=new T.Scene(),player=new T.Group();scene.add(player);
 const capital=createCapitalWorld(scene,player,{blocked:()=>false,notice(){},portfolio(){},cue(){}}),studies=capital.studies;scene.scale.setScalar(2);scene.updateMatrixWorld(true);scene.traverse(object=>{for(const bound of object.userData.staticCameraBounds??[])bound.applyMatrix4(scene.matrixWorld)});
 for(const aspect of [1440/960,390/844,320/740])for(const entry of studies.entries){
    player.position.set(entry.project.building.x,.8,entry.project.building.z+1.65);scene.updateMatrixWorld(true);const camera=new T.PerspectiveCamera(50,aspect,.1,18000),rig=createGameCamera(camera,scene,player),view=studyCameraView(aspect);rig.reset(view);for(let frame=0;frame<60;frame++)rig.update(1/60,false,defaultSettings,false,view.focusHeight);camera.updateMatrixWorld(true);
    for(const bound of capital.pavilion.root.userData.staticCameraBounds??[])assert.equal(bound.containsPoint(camera.position),false,'camera remains outside pavilion');
    for(const point of entry.points){const position=entry.group.localToWorld(point.clone()),projected=position.clone().project(camera);assert.ok(Math.abs(projected.x)<.9&&Math.abs(projected.y)<.9&&projected.z<1,JSON.stringify({study:entry.project.name,aspect,projected}));const ray=new T.Raycaster(camera.position,position.clone().sub(camera.position).normalize(),0,camera.position.distanceTo(position)-.7);assert.equal(ray.intersectObject(capital.pavilion.root,true).length,0,entry.project.name+' hidden by pavilion at '+aspect)}
 }disposeScene(scene);
});
