import * as T from 'three';
export function capsule(){const g=new T.Group();const outer=new T.MeshStandardMaterial({color:'#acc9ed',roughness:.35,metalness:.2});const shell=new T.Mesh(new T.CapsuleGeometry(.13,.32,4,10),outer);g.add(shell);const ring=new T.Mesh(new T.TorusGeometry(.14,.035,6,16),new T.MeshStandardMaterial({color:'#f9d87c'}));ring.rotation.x=Math.PI/2;g.add(ring);const light=new T.Mesh(new T.SphereGeometry(.09,8,8),new T.MeshStandardMaterial({color:'#d7ffee',emissive:'#7bffd3',emissiveIntensity:1}));light.position.y=.2;g.add(light);return g}
export function createCourier(){
 const root=new T.Group();root.name='Courier';const painted=new T.MeshStandardMaterial({color:'#969fe8',roughness:.83,metalness:0});
 const shape=(name:string,parent:T.Object3D,x:number,y:number,z:number,sx:number,sy:number,sz:number,color?:string)=>{const m=new T.Mesh(new T.SphereGeometry(1,24,18),color?new T.MeshStandardMaterial({color,roughness:.8}):painted);m.name=name;m.position.set(x,y,z);m.scale.set(sx,sy,sz);m.castShadow=true;parent.add(m);return m};
 const body=shape('body',root,0,.9,0,.78,.87,.63);shape('belly',root,0,.8,.45,.51,.52,.23,'#b3bafa');
 const head=new T.Group();head.name='Courier_Head';head.position.y=1.6;root.add(head);shape('head paint',head,0,0,0,.8,.69,.62);
 shape('navy face panel',head,0,-.04,.51,.64,.43,.16,'#182448');const leftEye=shape('left eye',head,-.24,.03,.665,.09,.145,.04,'#ffffff'),rightEye=shape('right eye',head,.24,.03,.665,.09,.145,.04,'#ffffff');
 const smilePoints=[new T.Vector3(-.19,-.16,.675),new T.Vector3(0,-.24,.695),new T.Vector3(.19,-.16,.675)];const smile=new T.Mesh(new T.TubeGeometry(new T.CatmullRomCurve3(smilePoints),20,.028,8,false),new T.MeshStandardMaterial({color:'white',roughness:.7}));smile.name='smile';head.add(smile);
 for(let i=0;i<5;i++)shape('tuft lobe '+i,head,(i-2)*.22,.55+Math.sin(i/4*Math.PI)*.15,-.02,.2,.25,.25);
 const leftArm=shape('left arm',root,-.76,.8,.12,.23,.38,.25),rightArm=shape('right arm',root,.76,.8,.12,.23,.38,.25);
 const leftFoot=shape('left foot',root,-.36,.13,.15,.28,.2,.36),rightFoot=shape('right foot',root,.36,.13,.15,.28,.2,.36);
 const tray=new T.Group();tray.name='diagnostic capsule tray';tray.position.set(0,.65,.88);root.add(tray);const base=new T.Mesh(new T.BoxGeometry(1.15,.12,.68),new T.MeshStandardMaterial({color:'#d8b27a',roughness:.8}));base.name='tray base';tray.add(base);const cargo:T.Group[]=[];for(let i=0;i<4;i++){const c=capsule();c.name='carried capsule '+(i+1);c.position.set((i%2-.5)*.48,.32,(Math.floor(i/2)-.5)*.3);tray.add(c);cargo.push(c)}
 let gesture='idle',gestureTime=0;const previous=new T.Vector3();let time=0;
 body.name='Courier_Body';leftArm.name='Courier_Arm_L';rightArm.name='Courier_Arm_R';leftFoot.name='Courier_Foot_L';rightFoot.name='Courier_Foot_R';
 return {root,parts:{body,head,leftEye,rightEye,smile,leftArm,rightArm,leftFoot,rightFoot,tray,cargo},gesture:(name:string)=>{gesture=name;gestureTime=1.6},update:(dt:number,inventory:number)=>{time+=dt;gestureTime=Math.max(0,gestureTime-dt);const moving=previous.distanceTo(root.position)>.005;previous.copy(root.position);const gait=moving?Math.sin(time*12):0;body.scale.y=.87+Math.sin(time*2.5)*.025;head.rotation.y=Math.sin(time*.65)*.12;head.rotation.z=gestureTime>0&&gesture==='curiosity'?.2:0;head.position.y=1.6+Math.sin(time*2.5)*.025;const blink=time%4.7>4.52?.015:.145;leftEye.scale.y=rightEye.scale.y=blink;leftFoot.position.z=.15+gait*.18;rightFoot.position.z=.15-gait*.18;leftArm.rotation.x=gait*.25;rightArm.rotation.x=-gait*.25;rightArm.rotation.z=gestureTime>0&&gesture==='greeting'?-1.7+Math.sin(time*17)*.25:0;leftArm.rotation.z=gestureTime>0&&(gesture==='pickup'||gesture==='delivery')?.65:0;tray.position.z=.88+(gestureTime>0&&gesture==='delivery'?Math.sin(gestureTime/1.6*Math.PI)*.3:0);cargo.forEach((c,i)=>c.visible=i<inventory)}};
}
