 'use client';
import {useEffect,useSyncExternalStore} from 'react';
import {exhibits} from './exhibit-state';
import {projects,portfolio} from './portfolio';
export function Demonstration({index,standalone=false}:{index:number;standalone?:boolean}){
 const exhibit=exhibits[index],project=projects[index];const state=useSyncExternalStore(exhibit.subscribe,exhibit.getSnapshot,exhibit.getSnapshot);
 useEffect(()=>{if(!standalone)return;let last=performance.now();const timer=setInterval(()=>{const now=performance.now();exhibit.tick(Math.min((now-last)/1000,.1));last=now},50);return()=>clearInterval(timer)},[exhibit,standalone]);
 return <section className="demo" aria-label={project.name+' demonstration'}><h3>Operate the exhibit</h3><label>{project.scenario.inputLabel}<select value={state.input} disabled={state.running} onChange={e=>exhibit.choose(e.target.value)}>{project.scenario.options.map(o=><option key={o}>{o}</option>)}</select></label><div className="demo-actions"><button onClick={exhibit.trigger} disabled={state.running}>{state.step<0?'Trigger':'Repeat'}</button><button onClick={exhibit.pause} disabled={!state.running}>{state.paused?'Resume':'Pause'}</button><button onClick={exhibit.reset}>Reset</button></div><p className="demo-status">{state.running?(state.paused?'Paused':'Running'):(state.step<0?'Ready':'Complete')} · Step {Math.max(0,state.step+1)} / {project.scenario.steps.length}</p><ol className="node-list">{project.nodes.map(n=><li key={n.id} className={state.active===n.id?'active':''}><strong>{n.label}</strong><span>{n.explanation}</span>{state.active===n.id&&<b>Active stage</b>}</li>)}</ol><output className="demo-result"><p>{state.explanation}</p><strong>{state.result}</strong>{project.scenario.mode==='react'&&state.active==='dom'&&<div className="render-card" style={{background:project.scenario.colors?.[state.committedInput]}}>Preview card · {state.committedInput}</div>}</output><small>{project.scenario.simplification}</small></section>
}
export function ProjectDetails({index,children}:{index:number;children?:React.ReactNode}){const p=projects[index];return <article className="project-record"><p className="eyebrow">{p.kind}</p><h2>{p.name}</h2><p>{p.description}</p>{children}<dl><dt>My contribution</dt><dd>{p.contribution}</dd><dt>Technology stack</dt><dd>{p.stack}</dd><dt>Engineering decisions</dt><dd><ul>{p.decisions.map(d=><li key={d}>{d}</li>)}</ul></dd><dt>Source & demo</dt><dd>{p.links.length?p.links.map(l=><a key={l.url} href={l.url} target="_blank" rel="noopener noreferrer">{l.label}</a>):'Links have not been supplied.'}</dd></dl></article>}
export {ResumeContent} from './resume-content';

