'use client';

import './friends-hub.css';
import {useEffect,useEffectEvent,useRef,useState,useSyncExternalStore} from 'react';
import {Dialog as DialogPrimitive} from '@base-ui/react/dialog';
import {Users,CarFront,Flag,Grid3X3,Crosshair,Table2,Rocket,Monitor,Trophy,Copy,LogOut,Mic,MicOff,Volume2,X,Play,Check,ArrowDownToLine,ArrowUpRight,DoorOpen,Eye,RotateCcw} from 'lucide-react';
import {Dialog,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {FriendsClient} from './friends-client';
import {FriendsVoice} from './friends-voice';
import type {FriendsActivityStatus} from './friends-activities';
import {FriendsComputer} from './friends-computer';
import {ChessGame,SudokuGame,TargetGame,PongGame,RaceControls,Podium,RecordTable,clockText,gameNames} from './friends-games-ui';
import {cars,friendColors,type PlayView,type ScoreGame,type RoomSnapshot} from '../lib/friends-protocol';
import {orbitPorts} from '../lib/orbit-course';

const tabs=[{id:'lobby',label:'Lobby',Icon:Users},{id:'race',label:'Race',Icon:CarFront},{id:'chess',label:'Chess',Icon:Flag},{id:'sudoku',label:'Sudoku',Icon:Grid3X3},{id:'targets',label:'Range',Icon:Crosshair},{id:'pong',label:'Ping pong',Icon:Table2},{id:'ship',label:'Starship',Icon:Rocket},{id:'computer',label:'Linux PC',Icon:Monitor},{id:'records',label:'Records',Icon:Trophy}] as const;
const isGame=(view:PlayView):view is ScoreGame=>view==='race'||view==='chess'||view==='sudoku'||view==='targets'||view==='pong';
function VoiceControls({voice}:{voice:FriendsVoice}){
 const state=useSyncExternalStore(voice.subscribe,voice.getState,voice.getState);
 return <div className="friends-voice"><div className="friends-inline"><button type="button" title={state.enabled?'Mute microphone':'Join voice'} aria-label={state.enabled?'Mute microphone':'Join voice'} aria-pressed={state.enabled} disabled={state.busy} onClick={()=>state.enabled?voice.stop():void voice.start()}>{state.enabled?<Mic size={18}/>:<MicOff size={18}/>}<span>{state.busy?'Connecting':state.enabled?'Voice on':'Voice off'}</span></button><small>{state.peers} connected</small></div><label><Volume2 size={16}/><input type="range" aria-label="Voice volume" min={0} max={1} step={.05} value={state.volume} onChange={event=>voice.volume(Number(event.target.value))}/></label>{state.error&&<div><output>{state.error}</output><button type="button" onClick={()=>voice.enableAudio()}><Volume2 size={16}/>Enable audio</button></div>}</div>;
}
export function FriendsHub({client,open,close,explore,view,changeView,visit,activity,changeCabin,reveal,disabled=false}:{client:FriendsClient;open:boolean;close:()=>void;explore:(destination:number)=>boolean;view:PlayView;changeView:(view:PlayView)=>void;visit:(view:PlayView)=>boolean;activity:FriendsActivityStatus;changeCabin:(value:boolean)=>void;reveal:(view:PlayView)=>void;disabled?:boolean}){
 const state=useSyncExternalStore(client.subscribe,client.getState,client.getServerState),room=state.room,self=room?.players.find(player=>player.id===state.id),host=room?.hostId===state.id,connected=state.status==='connected';
 const [name,setName]=useState(''),[code,setCode]=useState(''),[copied,setCopied]=useState(false),[localError,setLocalError]=useState(''),[voice]=useState(()=>new FriendsVoice(client)),[now,setNow]=useState(0),[pcVisited,setPcVisited]=useState(false);
 const lastMatch=useRef('');
 useEffect(()=>{voice.connect();return()=>voice.dispose()},[voice]);
 useEffect(()=>{let active=true;queueMicrotask(()=>{if(!active)return;try{setName(localStorage.getItem('kingdom.friends.name')??'')}catch{}setCode(new URLSearchParams(location.search).get('room')??'')});return()=>{active=false}},[]);
 const hasRoom=!!room;
 useEffect(()=>{if(!open&&!hasRoom)return;const timer=setInterval(()=>setNow(client.serverNow()),100);return()=>clearInterval(timer)},[open,hasRoom,client]);
 const receiveMatch=useEffectEvent(()=>{const snapshot=client.getState(),match=snapshot.room?.match;if(match&&match.id!==lastMatch.current){lastMatch.current=match.id;changeView(match.kind);if(match.kind==='race'&&match.participants.includes(snapshot.id))close();else reveal(match.kind)}});
 useEffect(()=>client.subscribe(()=>receiveMatch()),[client]);
 const select=(next:PlayView)=>{changeView(next);setLocalError('');if(next==='computer')setPcVisited(true)};
 const inShip=!!room?.ship.crew.includes(state.id),match=room?.match,showMatch=match&&match.kind===view,finished=showMatch&&match.phase==='finished';
 async function copyInvite(){
  if(!room)return;
  try{const url=new URL(location.href);url.searchParams.set('room',room.code);url.hash='friends';await navigator.clipboard.writeText(url.toString());setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{setLocalError('Clipboard access is unavailable. The invite code can be selected directly.')}
 }
 function start(){if(room)client.send({type:'start',...room.setup})}
 function configure(kind:ScoreGame){if(room&&host)client.send({type:'configure',setup:{...room.setup,kind}})}
 function land(){
  if(!room||room.ship.destination!==null||!inShip)return;
  if(explore(room.ship.current)){client.send({type:'ship-leave'});close()}else setLocalError('Return outdoors in the main world before exploring this planet.');
 }
 const readyCount=room?.players.filter(player=>player.connected&&player.ready).length??0;
 const canStart=connected&&host&&!!self?.ready&&(!match||match.phase==='finished')&&!inShip&&!room?.ship.crew.length&&(room?.setup.kind==='chess'||room?.setup.kind==='pong'?readyCount===2:readyCount>0);
 const lobby=(current:RoomSnapshot)=><section className="friends-lobby-controls"><div className="friends-section-heading"><div><small>NEXT ROUND</small><h2>{gameNames[current.setup.kind]}</h2></div><span className="friends-ready-count">{readyCount} / {current.setup.kind==='chess'||current.setup.kind==='pong'?2:current.players.length} ready</span></div>
 <div className="friends-game-options">{(Object.keys(gameNames) as ScoreGame[]).map(kind=><button key={kind} type="button" aria-pressed={current.setup.kind===kind} disabled={!host||!!match&&match.phase!=='finished'} onClick={()=>configure(kind)}>{tabs.find(tab=>tab.id===kind)?.label}</button>)}</div>
 <div className="friends-inline">{current.setup.kind==='race'&&<label>Laps<input type="number" aria-label="Race laps" min={1} max={10} value={current.setup.laps} disabled={!host||!!match&&match.phase!=='finished'} onChange={event=>{const laps=Number(event.target.value);if(Number.isInteger(laps)&&laps>=1&&laps<=10)client.send({type:'configure',setup:{...current.setup,laps}})}}/></label>}{current.setup.kind==='chess'&&<fieldset className="friends-segmented" aria-label="Chess clock">{[10,30].map(minutes=><button key={minutes} type="button" aria-label={`${minutes} minute chess`} aria-pressed={current.setup.minutes===minutes} disabled={!host||!!match&&match.phase!=='finished'} onClick={()=>client.send({type:'configure',setup:{...current.setup,minutes}})}>{minutes} min</button>)}</fieldset>}
 <button type="button" className="friends-primary" aria-pressed={!!self?.ready} disabled={!connected||disabled||!!match&&match.phase!=='finished'||inShip} onClick={()=>{if(self?.ready||visit(current.setup.kind))client.send({type:'ready',ready:!self?.ready});else setLocalError('Return outdoors and leave your vehicle before joining a game.')}}><Check size={17}/>{self?.ready?'Ready':'Ready up'}</button>{host&&<button type="button" className="friends-start" disabled={!canStart||disabled} onClick={start}><Play size={17}/>Start round</button>}</div>
 {current.setup.kind==='race'&&<div className="friends-garage"><h3>Your car</h3><div className="friends-car-options">{cars.map(car=><button key={car.id} type="button" aria-pressed={self?.car===car.id} disabled={!!match&&match.phase!=='finished'} onClick={()=>client.send({type:'profile',car:car.id})}><CarFront style={{color:car.color}} size={30}/><span>{car.name}</span><small>{Math.round(car.speed*3.6)} km/h</small></button>)}</div></div>}
 </section>;
 return <>
 {room&&!open&&<div className="friends-live-hud"><div className="friends-live-status"><button type="button" title="Friends and games" aria-label="Friends and games" onClick={()=>reveal(activity.kind==='ship'?'ship':activity.kind==='race'?'race':'lobby')}><Users size={17}/><span>{room.players.filter(player=>player.connected).length} / 5</span></button><VoiceControls voice={voice}/></div>
 {activity.kind==='race'&&match?.kind==='race'&&<><output className="friends-race-timer">{match.phase==='countdown'?Math.max(1,Math.ceil((match.startsAt-now)/1000)):`LAP ${Math.min(match.laps??1,Math.floor((match.racers?.find(racer=>racer.id===state.id)?.distance??0)/(match.length??1))+1)} / ${match.laps}`}</output><RaceControls client={client} enabled={!disabled&&connected&&match.phase==='running'&&match.participants.includes(state.id)&&match.racers?.find(racer=>racer.id===state.id)?.finishMs===null}/></>}
 {activity.kind==='ship'&&<div className="friends-live-ship"><span>{room.ship.destination!==null?'In flight / ':''}{orbitPorts[room.ship.destination??room.ship.current].name}</span><button type="button" title="Starship destinations" aria-label="Starship destinations" onClick={()=>reveal('ship')}><Rocket size={17}/>Destinations</button><button type="button" title={activity.cabin?'Exterior view':'Cabin view'} aria-label={activity.cabin?'Exterior view':'Cabin view'} onClick={()=>changeCabin(!activity.cabin)}><Eye size={17}/></button><button type="button" disabled={room.ship.destination!==null} onClick={land}><ArrowDownToLine size={17}/>Disembark</button></div>}
 </div>}
 <Dialog open={open} modal={false} onOpenChange={value=>{if(!value)close()}}><DialogPrimitive.Portal><DialogPrimitive.Popup className="friends-hub friends-inworld" data-board={isGame(view)&&view!=='race'||view==='computer'}><header className="friends-header"><div><DialogTitle>Friends & games</DialogTitle><DialogDescription className="sr-only">Multiplayer activities in Motherboard Commons.</DialogDescription><span className="friends-connection" data-state={state.status}>{connected?`${room?.players.filter(player=>player.connected).length} / 5 connected`:state.status==='idle'?'MOTHERBOARD COMMONS':state.status.toUpperCase()}</span></div><div className="friends-header-actions">{room&&<button type="button" title={copied?'Invite copied':'Copy invite'} aria-label={copied?'Invite copied':'Copy invite'} onClick={()=>void copyInvite()}>{copied?<Check size={18}/>:<Copy size={18}/>}</button>}{room&&<button type="button" title="Leave room" aria-label="Leave room" onClick={()=>{voice.stop();client.leave();changeView('lobby')}}><LogOut size={18}/></button>}<button type="button" title="Return to the world" aria-label="Return to the world" onClick={close}><X size={20}/></button></div></header>
 {(state.error||localError)&&<div className="friends-error" role="alert"><span>{localError||state.error}</span><button type="button" title="Dismiss error" aria-label="Dismiss error" onClick={()=>{setLocalError('');client.clearError()}}><X size={16}/></button></div>}
 {!room?<div className="friends-welcome"><form className="friends-join" onSubmit={event=>{event.preventDefault();voice.stop();client.join(code.trim()?'join':'create',name,code)}}><h2>Private room</h2><label>Player name<input aria-label="Player name" maxLength={24} required value={name} onChange={event=>setName(event.target.value)} autoComplete="off"/></label><label>Invite code<input aria-label="Invite code" maxLength={24} pattern="[a-fA-F0-9]{24}" value={code} onChange={event=>setCode(event.target.value.toUpperCase())} autoComplete="off" spellCheck={false}/></label><button type="submit" className="friends-primary" disabled={!name.trim()||state.status==='connecting'||state.status==='reconnecting'}><Users size={17}/>{code.trim()?'Join room':'Create room'}</button>{code&&<button type="button" onClick={()=>{voice.stop();client.forgetIdentity(code,name);client.join('join',name,code)}} disabled={!name.trim()||state.status==='connecting'}><RotateCcw size={16}/>Join as a new guest</button>}</form></div>:<>
 <nav className="friends-tabs" aria-label="Multiplayer activities">{tabs.map(({id,label,Icon})=><button key={id} type="button" title={label} aria-label={label} aria-current={view===id?'page':undefined} onClick={()=>select(id)}><Icon size={18}/><span>{label}</span>{match?.kind===id&&match.phase!=='finished'&&<i/>}</button>)}</nav>
 <div className="friends-layout"><aside className="friends-sidebar"><section className="friends-roster"><div className="friends-section-heading"><h2>Crew</h2><span>{room.players.length} / 5</span></div><ol>{room.players.map(player=><li key={player.id} data-player-id={player.id} data-connected={player.connected}><span className="friends-avatar-dot" style={{backgroundColor:player.color}}/><div><strong>{player.name}{player.id===state.id?' (you)':''}</strong><small>{!player.connected?'Reconnecting':room.ship.crew.includes(player.id)?room.ship.captain===player.id?'Captain':'On board':player.id===room.hostId?'Host':player.ready?'Ready':'Guest'}</small></div>{player.voice&&<Mic size={14}/>}<Check size={16} className={player.ready?'friend-ready':'friend-not-ready'}/></li>)}</ol><fieldset className="friends-swatches" aria-label="Character color">{friendColors.map(color=><button key={color} type="button" aria-label={`Character color ${color}`} title={color} aria-pressed={self?.color===color} style={{backgroundColor:color}} disabled={!connected||room.players.some(player=>player.id!==state.id&&player.color===color)} onClick={()=>client.send({type:'profile',color})}>{self?.color===color&&<Check size={14}/>}</button>)}</fieldset></section>
 {voice&&<VoiceControls voice={voice}/>}<div className="friends-room-code"><span>Invite code</span><code>{room.code}</code></div><RecordTable title={gameNames[isGame(view)?view:room.setup.kind]} record={room.records[isGame(view)?view:room.setup.kind]}/></aside>
 <div className="friends-main" data-view={view}>
 <div className="friends-station-toolbar"><button type="button" disabled={activity.active||disabled} onClick={()=>{if(visit(view))close();else setLocalError('Return outdoors and leave your vehicle first.')}}><ArrowUpRight size={16}/>Visit {tabs.find(tab=>tab.id===view)?.label==='Lobby'?'game stations':tabs.find(tab=>tab.id===view)?.label}</button>{activity.active&&<button type="button" onClick={close}><Eye size={16}/>Return to {activity.kind==='race'?'race':'ship'}</button>}</div>
 {view==='race'&&showMatch&&<div className="friends-race-results"><h2>{match.phase==='finished'?'Race complete':'Orbital Circuit'}</h2><ol>{[...match.racers??[]].sort((first,second)=>second.distance-first.distance).map((racer,index)=><li key={racer.id}><b>{index+1}</b><span>{room.players.find(player=>player.id===racer.id)?.name??'Disconnected'}</span><small>{racer.dnf?'DNF':racer.finishMs!==null?clockText(racer.finishMs):`${Math.floor(racer.distance/(match.length??1))} / ${match.laps} laps`}</small></li>)}</ol></div>}
 {(view==='lobby'||isGame(view)&&!showMatch)&&lobby(room)}
 {showMatch&&view==='chess'&&<ChessGame key={match.id} match={match} players={room.players} id={state.id} client={client}/>}
 {showMatch&&view==='sudoku'&&<SudokuGame key={match.id} match={match} id={state.id} client={client}/>}
 {showMatch&&view==='targets'&&<TargetGame key={match.id} match={match} id={state.id} client={client}/>}
 {showMatch&&view==='pong'&&<PongGame key={match.id} match={match} players={room.players} id={state.id} client={client}/>}
 {showMatch&&match.phase==='countdown'&&view!=='race'&&<output className="friends-countdown">{Math.max(1,Math.ceil((match.startsAt-now)/1000))}</output>}
 {showMatch&&match.phase==='running'&&(view==='targets'||view==='sudoku')&&<output className="friends-match-time">{clockText(match.endsAt-now)}</output>}
 {finished&&<div className="friends-results"><Podium rows={match.podium} reason={match.reason}/>{host&&<button type="button" onClick={()=>{client.send({type:'reset'});select('lobby')}}><RotateCcw size={17}/>Back to lobby</button>}</div>}
 {view==='ship'&&<section className="friends-ship-controls"><div className="friends-inline"><button type="button" className="friends-primary" disabled={!connected||disabled||room.ship.destination!==null||!!match&&match.phase!=='finished'} onClick={()=>{if(inShip)land();else if(visit('ship')){client.send({type:'ship-board'});close()}else setLocalError('Return outdoors and leave your vehicle first.')}}>{inShip?<DoorOpen size={17}/>:<ArrowUpRight size={17}/>} {inShip?'Disembark':'Board starship'}</button><span>{room.ship.crew.length} / 5 aboard</span><button type="button" aria-pressed={activity.cabin} onClick={()=>changeCabin(!activity.cabin)}><Eye size={17}/>{activity.cabin?'Exterior':'Cabin view'}</button>{inShip&&<button type="button" disabled={room.ship.destination!==null} onClick={land}><ArrowDownToLine size={17}/>Explore planet</button>}</div><div className="friends-ports">{orbitPorts.map((port,index)=><button key={port.name} type="button" disabled={!connected||room.ship.captain!==state.id||room.ship.destination!==null||room.ship.current===index} onClick={()=>{client.send({type:'ship-travel',destination:index});close()}}><span style={{backgroundColor:port.color}}/><span>{port.name}</span>{room.ship.current===index&&<small>Docked</small>}</button>)}</div></section>}
 {(pcVisited||view==='computer')&&<div hidden={view!=='computer'}><FriendsComputer visible={open&&view==='computer'}/></div>}
 {view==='records'&&<section className="friends-records-page"><h2>Room records</h2>{(Object.keys(gameNames) as ScoreGame[]).map(kind=><RecordTable key={kind} title={gameNames[kind]} record={room.records[kind]}/>)}</section>}
 </div></div></>}
 </DialogPrimitive.Popup></DialogPrimitive.Portal></Dialog></>;
}
