import type {SoundCue} from './audio-score';
import {createPacketPress} from './packet-press-asset';
import * as T from 'three';
import {DeliveryRound,type DeliverySnapshot} from './delivery-state';
import {createCourier} from './courier';
import {KingdomVoices} from './kingdom-voices';
import {encounters,type Encounter} from './encounter-config';
import {createDialogueDeck} from './resident-dialogue';
export {encounters,type Encounter} from './encounter-config';
export function createLivingWorld(scene:T.Scene,player:T.Group,courier:ReturnType<typeof createCourier>,callbacks:{initialDelivery?:DeliverySnapshot|null;onDelivery?:(s:DeliverySnapshot)=>void;onEncounter?:(e:Encounter|null)=>void;onSubtitle?:(s:string)=>void;onSound?:(cue:SoundCue)=>void}){
 const round=new DeliveryRound();if(callbacks.initialDelivery)round.restore(callbacks.initialDelivery);const voices=new KingdomVoices(),root=new T.Group();scene.add(root);let time=0,current:Encounter|null=null,lastId='',reaction='',reactionUntil=0;const talks=new Map<string,ReturnType<typeof createDialogueDeck>>();
 const materialCache=new Map<string,T.MeshStandardMaterial>();const sphere=new T.SphereGeometry(1,16,12);
 const material=(color:string,glow=0)=>{const key=color+'/'+glow;let m=materialCache.get(key);if(!m){m=new T.MeshStandardMaterial({color,roughness:.82,metalness:.05,emissive:color,emissiveIntensity:glow});materialCache.set(key,m)}return m};
 function orb(g:T.Object3D,name:string,x:number,y:number,z:number,sx:number,sy:number,sz:number,color:string,glow=0){const m=new T.Mesh(sphere,material(color,glow));m.name=name;m.position.set(x,y,z);m.scale.set(sx,sy,sz);m.castShadow=true;m.receiveShadow=true;g.add(m);return m}
 function box(g:T.Object3D,x:number,y:number,z:number,w:number,h:number,d:number,color:string,glow=0){const m=new T.Mesh(new T.BoxGeometry(w,h,d),material(color,glow));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;g.add(m);return m}
 function tube(g:T.Object3D,points:T.Vector3[],color:string,r=.08){const m=new T.Mesh(new T.TubeGeometry(new T.CatmullRomCurve3(points),24,r,8,false),material(color));g.add(m);return m}
 function sign(text:string,x:number,y:number,z:number){const canvas=document.createElement('canvas');canvas.width=768;canvas.height=100;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#e8f2dd';ctx.font='bold 30px Arial';ctx.textAlign='center';ctx.fillText(text,384,62);const m=new T.Sprite(new T.SpriteMaterial({map:new T.CanvasTexture(canvas),depthTest:true}));m.position.set(x,y,z);m.scale.set(8,1.04,1);root.add(m);return m}
 const actors=new Map<string,{group:T.Group;limbs:T.Object3D[];skin?:T.Mesh}>();
 for(const e of encounters.filter(e=>e.kind==='resident')){const g=new T.Group();g.position.set(e.x,.55,e.z);root.add(g);const limbs:T.Object3D[]=[];let skin:T.Mesh|undefined;
 if(e.id==='owl'){orb(g,'owl body',0,1,0,.68,.9,.6,'#b2bbd3');orb(g,'owl head',0,1.9,0,.8,.68,.6,'#8d9cc0');for(const x of [-.3,.3]){orb(g,'eye disc',x,1.95,.52,.33,.35,.1,'#f0dfad');orb(g,'pupil',x,1.95,.62,.1,.16,.05,'#192742');limbs.push(orb(g,'wing',Math.sign(x)*.7,.95,0,.25,.65,.25,'#7786b0'))}orb(g,'beak',0,1.68,.7,.15,.21,.22,'#edb66d');box(g,0,.55,.65,.8,.12,.55,'#639b88')}
 if(e.id==='chameleon'){skin=orb(g,'color changing body',0,1,0,.7,.7,.95,'#9ce09b');orb(g,'head',0,1.55,.55,.62,.5,.55,'#95dda6');for(const x of [-.48,.48]){orb(g,'eye turret',x,1.7,.73,.23,.25,.23,'#d9e99c');orb(g,'pupil',x,1.72,.94,.07,.1,.03,'#172b37');limbs.push(orb(g,'hand',x,.5,.45,.21,.3,.25,'#8ccea1'))}tube(g,[new T.Vector3(0,.7,-.7),new T.Vector3(.8,.8,-1.1),new T.Vector3(1,.95,-.4),new T.Vector3(.6,1,-.3)],'#91d49f',.16);box(g,.9,1,.3,.1,1.5,.1,'#d6b184')}
 if(e.id==='cloud'){for(let i=0;i<5;i++)orb(g,'cloud lobe',Math.cos(i*1.26)*.65,1.65+Math.sin(i*1.26)*.3,0,.65,.58,.45,'#abb4d4');for(const x of [-.3,.3]){orb(g,'eye',x,1.65,.46,.08,.11,.05,'#1c2b45');const brow=box(g,x,1.9,.45,.3,.07,.1,'#27354b');brow.rotation.z=-Math.sign(x)*.25}box(g,0,1.36,.48,.38,.06,.08,'#25344a');for(let i=0;i<3;i++)limbs.push(orb(g,'rain bead',-.5+i*.5,.7,0,.06,.18,.06,'#a5d9f1',.3))}
 if(e.id==='gopher'){orb(g,'burrow',0,.05,0,1,.12,.8,'#263c36');skin=orb(g,'gopher body',0,.75,0,.55,.7,.48,'#c89f7a');orb(g,'snout',0,1,.4,.35,.3,.3,'#efcda5');for(const x of [-.25,.25]){orb(g,'eye',x,1.2,.43,.06,.09,.04,'#202d36');orb(g,'ear',x,1.42,0,.15,.2,.12,'#b78c69')}limbs.push(orb(g,'paw',.55,.6,.1,.18,.25,.18,'#b78c69'))}
 if(e.id==='tortoises'){for(let i=0;i<3;i++){const family=new T.Group();family.position.x=(i-1)*1.3;family.scale.setScalar(i===1?1:.57);g.add(family);orb(family,'shell',0,.65,0,.8,.63,.95,i===1?'#91ad7b':'#b5c58e');for(let j=0;j<3;j++)box(family,-.45+j*.45,.98,0,.035,.05,1.2,'#527961');orb(family,'head',0,.45,.95,.3,.3,.4,'#c8d69f');for(const x of [-.16,.16])orb(family,'eye',x,.52,1.28,.035,.06,.03,'#162d29');for(const x of [-.6,.6])for(const z of [-.5,.5])limbs.push(orb(family,'foot',x,.12,z,.2,.18,.28,'#b5c48c'))}}
 if(e.id==='birds'){for(let i=0;i<5;i++){const bird=new T.Group();bird.position.set((i-2)*.55,1.8+i*.18,Math.sin(i));g.add(bird);box(bird,0,0,0,.22,.22,.3,'#b6ffdb',.8);const l=box(bird,-.22,0,0,.35,.07,.18,'#c7ffe6',1),r=box(bird,.22,0,0,.35,.07,.18,'#c7ffe6',1);limbs.push(l,r)}}
 if(skin)skin.material=(skin.material as T.Material).clone();actors.set(e.id,{group:g,limbs,skin});sign(e.name,e.x,4,e.z)
 }
 // Each curiosity stop has a short ground-level connection to the existing hub.
 const curios=new Map<string,T.Group>();const bells:T.Mesh[]=[];const crystals:T.Mesh[]=[];
 for(const e of encounters.filter(e=>e.kind==='curiosity')){const g=new T.Group();g.position.set(e.x,.2,e.z);root.add(g);curios.set(e.id,g);sign(e.name,e.x,4,e.z);const a=new T.Vector3(0,.1,19),b=new T.Vector3(e.x,.1,e.z);tube(root,[a,a.clone().lerp(b,.5),b],'#a9bc88',.09);
 if(e.id==='capacitors'){for(let i=0;i<5;i++){const m=orb(g,'musical capacitor',i*.65-1.3,.6+i*.17,0,.25,.6+i*.17,.25,['#a8c2ed','#96d9c3','#e4bc8d','#c5a8e0','#a4d49c'][i]);bells.push(m);orb(g,'metal top',i*.65-1.3,1.2+i*.34,0,.27,.08,.27,'#e0e8cb')}}
 if(e.id==='baths'){orb(g,'bath rim',0,.15,0,2,.3,1.4,'#81aa9d');orb(g,'cooling water',0,.32,0,1.7,.06,1.15,'#7bcbe3',.25);for(let i=0;i<4;i++){const ring=new T.Mesh(new T.TorusGeometry(.3+i*.28,.025,6,32),material('#b6f0ed',.3));ring.rotation.x=Math.PI/2;ring.position.y=.4;g.add(ring)}}
 if(e.id==='kiln'){box(g,0,.9,0,2.2,1.8,1.8,'#aa7d65');box(g,0,.8,.92,1.4,1,.1,'#f2b16c',.8);box(g,.7,2,0,.5,1.2,.6,'#796856');const artifact=orb(g,'compiled object',0,.3,1.7,.35,.35,.35,'#bfffe1',.5);artifact.name='output'}
 if(e.id==='woodland'){for(let i=0;i<5;i++){const x=(i-2)*.85;tube(g,[new T.Vector3(x,0,0),new T.Vector3(x+.3,1.8,.2),new T.Vector3(x*.6,3,.5)],'#8dac82',.1);for(let j=0;j<3;j++)orb(g,'cable leaf',x+(j%2?.35:-.35),1+j*.55,0,.48,.17,.25,'#76ba9d')}}
 if(e.id==='crystals'){for(let i=0;i<8;i++){const m=new T.Mesh(new T.OctahedronGeometry(.4,0),material('#a3dbe5',.3));m.position.set((i%2?1:-1)*.9,.5,-2+i*.6);m.scale.y=1.7;g.add(m);crystals.push(m)}}
 if(e.id==='cinema'){box(g,0,1.8,0,4.8,3,.3,'#333b62');box(g,0,1.8,.2,4.3,2.5,.1,'#122844');for(let i=0;i<3;i++)box(g,-1.2+i*1.2,.3,2,.8,.5,.7,'#8d7baf');const film=new T.Mesh(new T.IcosahedronGeometry(.6,0),material('#d9b1f2',.5));film.name='film';film.position.set(0,1.8,.5);g.add(film);for(let i=0;i<3;i++){const star=orb(g,'orbit bit '+i,0,1.8,.5,.14,.14,.14,['#f0d58c','#b3f5d3','#b8b7fa'][i],.6);star.name='orbit bit '+i}}
 }
 const press=createPacketPress(root);
 const announce=(text:string,seed:number,gesture='greeting',celebrate=false)=>{callbacks.onSubtitle?.(text);callbacks.onSound?.(gesture==='pickup'?'pickup':gesture==='delivery'?'delivery':gesture==='curiosity'?'machine':'creature');voices.speak(seed,celebrate);courier.gesture(gesture)};
 const unsubscribe=round.subscribe(()=>callbacks.onDelivery?.(round.snapshot));callbacks.onDelivery?.(round.snapshot);
 function nearest(){return encounters.filter(e=>Math.hypot(e.x-player.position.x,e.z-player.position.z)<(e.id==='press'?4:3.2)).sort((a,b)=>Math.hypot(a.x-player.position.x,a.z-player.position.z)-Math.hypot(b.x-player.position.x,b.z-player.position.z))[0]??null}
 function interact(){const e=nearest();if(!e)return false;reaction=e.id;reactionUntil=time+3;if(e.id==='press'){if(round.snapshot.phase==='idle'){round.prepare();announce('Packet Press: charging four diagnostic capsules.',1,'curiosity')}else if(round.snapshot.phase==='ready'&&round.collect()){announce(round.snapshot.message,1,'pickup')}else announce(round.snapshot.phase==='complete'?'Round complete. Use Start another round when you are ready.':round.snapshot.phase==='preparing'?'Charging… watch the four indicators.':'Tray empty. Your remaining capsules are with you or their recipients.',1);return true}let dialogue=talks.get(e.id);if(!dialogue){dialogue=createDialogueDeck('home',Math.random,e.dialogue);talks.set(e.id,dialogue)}round.discover(e.id,e.name);announce(e.name+': '+(e.kind==='curiosity'?e.dialogue[Math.floor(Math.random()*e.dialogue.length)]:dialogue.next()),encounters.indexOf(e),e.kind==='curiosity'?'curiosity':'greeting');return true}
 function deliver(){const e=nearest();if(!e?.recipient)return;round.discover(e.id,e.name);if(round.deliver(e.id)){reaction=e.id;reactionUntil=time+3;announce(e.name+': Diagnostic received. Thank you, little courier! '+(round.snapshot.phase==='complete'?'All four deliveries complete!':'One capsule is plenty for this round.'),encounters.indexOf(e),'delivery',round.snapshot.phase==='complete')}else announce(e.name+': '+(round.snapshot.delivered.includes(e.id)?'Already received mine this round. Stay and chat!':'You have no capsule to deliver. You are still welcome here.'),encounters.indexOf(e))}
 return {round,volume:(v:number)=>voices.setVolume(v),blocked:(x:number,z:number)=>{if(player.position.y>3)return false;if(press.blocked(x,z))return true;return encounters.some(e=>{if(e.id==='press'||e.id==='birds'||e.id==='woodland'||e.id==='crystals'||e.id==='baths')return false;const w=e.id==='cinema'?2.8:e.id==='capacitors'?1.8:e.id==='kiln'?1.5:.9;const depth=e.id==='cinema'?.6:1.1;return Math.abs(x-e.x)<w&&Math.abs(z-e.z)<depth})},interact,deliver,nextRound:()=>{if(nearest()?.id==='press'&&round.nextRound())announce(round.snapshot.message,1,'greeting')},sound:(enabled:boolean)=>voices.enable(enabled),dispose:()=>{unsubscribe();voices.dispose();press.dispose()},update:(dt:number,inside:boolean,reduced=false)=>{time+=reduced?0:dt;round.tick(dt);courier.update(reduced?0:dt,round.snapshot.inventory);current=inside?null:nearest();if((current?.id??'')!==lastId){lastId=current?.id??'';callbacks.onEncounter?.(current)}const phase=round.snapshot.phase;press.update(round.snapshot,round.progress);
 actors.forEach((actor,id)=>{actor.group.visible=Math.hypot(actor.group.position.x-player.position.x,actor.group.position.z-player.position.z)<38;if(!actor.group.visible)return;const active=reaction===id&&time<reactionUntil;actor.group.rotation.y=Math.sin(time*.7)*.13;actor.group.position.y=.55+(active?Math.sin(time*8)*.08:Math.sin(time*2)*.025);actor.limbs.forEach((limb,i)=>limb.rotation.z=id==='birds'?Math.sin(time*12+i)*.6:active?Math.sin(time*8+i)*.25:Math.sin(time*2+i)*.05);if(id==='chameleon'&&actor.skin)(actor.skin.material as T.MeshStandardMaterial).color.setHSL((time*.025+(active?.3:0))%1,.45,.65);if(id==='gopher'){const hiding=!active&&time%9>6;actor.group.scale.y=hiding?.08:1}if(id==='cloud')actor.group.position.y+=Math.sin(time)*.15});
 curios.forEach((g,id)=>{g.visible=Math.hypot(g.position.x-player.position.x,g.position.z-player.position.z)<42;if(!g.visible)return;const active=reaction===id&&time<reactionUntil;if(id==='baths')g.children.forEach((m,i)=>{if(m instanceof T.Mesh&&m.geometry instanceof T.TorusGeometry){m.scale.setScalar(1+Math.sin(time*2+i)*.12+(active?.3:0))}});if(id==='woodland')g.rotation.z=Math.sin(time)*(active?.06:.01);if(id==='kiln'){const output=g.getObjectByName('output')!;output.position.y=.35+(active?Math.sin(time*4)*.2:0);output.visible=round.snapshot.discoveries.includes(id)}if(id==='cinema'){const film=g.getObjectByName('film')!;film.rotation.set(time*.7,time*.9,time*.3);film.position.x=Math.sin(time)*1.2;film.scale.setScalar(.65+Math.sin(time*.7)*.25);film.visible=time%16<8;for(let i=0;i<3;i++){const star=g.getObjectByName('orbit bit '+i)!;star.visible=!film.visible;star.position.set(Math.cos(time+i*2.1)*1.4,1.8+Math.sin(time+i*2.1)*.8,.5)}}});bells.forEach((m,i)=>m.scale.y=(.6+i*.17)*(1+(reaction==='capacitors'&&time<reactionUntil?Math.sin(time*12+i)*.15:0)));crystals.forEach((m,i)=>(m.material as T.MeshStandardMaterial).emissiveIntensity=.3+(reaction==='crystals'&&time<reactionUntil?(.5+Math.sin(time*6+i)*.3):0));
 return current?current.id==='press'?(phase==='idle'?'E · Prepare diagnostic capsules':phase==='ready'&&round.snapshot.stock?'E · Collect a capsule':phase==='complete'?'Round complete · Start another round at the press':'E · Inspect Packet Press'):'E · '+(current.kind==='resident'?'Talk to ':'Discover ')+current.name:null}};
}
