'use client';
import {useState} from 'react';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {districts} from './world';
import {KingdomSimulation} from './simulation';
import {portfolio,projects} from './portfolio';
const notes=['The Packet Press is a fictional boot-time guide. Deliveries are optional; every district and exhibit is already open.','A FIFO ready queue and three non-preemptive cores. Real CPUs use instruction pipelines, interrupts, caches, and more complex scheduling.','Twelve equal-size slots represent explicitly allocated volatile memory. Real RAM uses byte addresses and does not move shelves; data here resets on reload.','Three.js renders actual geometry, PBR materials, and lights immediately. This is a simplified artist workflow, not a GPU pipeline debugger.','A fixed, lossless route illustrates forwarding hops. Real networks choose routes using forwarding tables and may drop, reorder, or retry packets.','A binary search over sorted index keys illustrates pruning. Production database indexes commonly use B-trees, with pages, concurrency control, and disk access.','Two desired replicas on three eligible one-slot nodes. Readiness gates endpoints; a controller creates replacements and a scheduler selects capacity. Timing and failure detection are simplified.','A keyed append-only log with three partitions and two independent groups. Order is guaranteed within a partition only. Offsets are the next event to read; retention is the current session, capped at 90 events.'];
const greetings=['“Oh! A new process. Welcome home.”','“Leave a task with me. We’ll find it a core.”','“Memories are borrowed. Return them when you’re done.”','“A few vertices can become anything.”','“Follow the cargo. Every switch has a story.”','“A good index knows where to look.”','“One house sleeps. Another keeps the lights on.”','“New events arrive. Old stories remain.”'];
export {greetings};
function Choice({label,value,values,onChange}:{label:string,value:string,values:string[],onChange:(s:string)=>void}){return <label className="field"><span>{label}</span><Select value={value} onValueChange={v=>v&&onChange(v)}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{values.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></label>}
export function Panels({panel,close,sim,refresh,game,go}:{panel:number|string|null,close:()=>void,sim:KingdomSimulation,refresh:()=>void,game:any,go:(i:number)=>void}){
 const [slot,setSlot]=useState(0),[dest,setDest]=useState('RAM Library'),[record,setRecord]=useState('110'),[eventKey,setEventKey]=useState('garden'),[value,setValue]=useState('seed.planted'),[group,setGroup]=useState('garden'),[partition,setPartition]=useState('0');
 const act=(fn:()=>unknown)=>{try{fn()}catch(e){sim.message=(e as Error).message}refresh()};const n=typeof panel==='number'?panel:-1;
 return <Sheet open={panel!==null} onOpenChange={v=>!v&&close()} modal={false}><SheetContent className="machine-panel" showCloseButton><div className="eyebrow">{n>=0?'LIVE LOCAL SIMULATION':'KINGDOM OS / PORTFOLIO'}</div><SheetTitle>{n>=0?districts[n].name:panel==='projects'?'Project buildings':'System Information'}</SheetTitle><SheetDescription>{n>=0?greetings[n]:panel==='projects'?'Walk inside the architecture. These sample exhibits are ready to replace with your real projects.':'A résumé, viewed from inside the machine.'}</SheetDescription>
 {n===0&&<><div className="pip-note"><b>Pip · Workshop keeper</b><p>“You’re a little process in a very big computer. Walk with WASD, drag the world to look around, and press E when you meet a machine.”</p><p>“Press a welcome packet, then bring it to the RAM Library. Or wander off. Curiosity is a perfectly good plan.”</p></div><button className="action" onClick={()=>act(()=>{sim.pressed=true;game?.press();sim.message='Welcome packet pressed. Follow the mint path to RAM Library.'})}>{sim.pressed?'Press another packet':'Operate Packet Press'}</button><button className="secondary" onClick={()=>{close();go(2)}}>Show me the RAM Library →</button></>}
 {n===1&&<><div className="core-grid">{[0,1,2].map(c=>{const j=sim.jobs.find(j=>j.core===c&&j.status==='running');return <div key={c} className={j?'busy':''}><small>CORE {c+1}</small><b>{j?'Job #'+j.id:'Available'}</b><span>{j?(3-j.remaining).toFixed(1)+' / 3.0s':'Ready for work'}</span></div>})}</div><button className="action" onClick={()=>act(()=>sim.submit())}>Submit a small job +</button><div className="log"><b>READY QUEUE</b><p>{sim.jobs.filter(j=>j.status==='queued').map(j=>'#'+j.id).join(' → ')||'Empty · cores are ready'}</p><b>COMPLETED</b><p>{sim.jobs.filter(j=>j.status==='complete').slice(-8).map(j=>'#'+j.id+' ✓').join(' · ')||'No completed jobs yet'}</p></div></>}
 {n===2&&<><button className="action" onClick={()=>act(()=>sim.allocate())}>Allocate temporary data +</button><div className="memory-grid">{sim.slots.map((s,i)=><button key={i} onClick={()=>setSlot(i)} className={(s?'occupied ':'')+(slot===i?'chosen':'')} aria-label={`Inspect slot ${i}`}><small>0x{(i*16).toString(16).padStart(2,'0')}</small>{s?'●':'○'}</button>)}</div><div className="log"><b>ADDRESS 0x{(slot*16).toString(16).padStart(2,'0')}</b><p>{sim.slots[slot]||'Free slot · available for allocation'}</p></div><button className="secondary" onClick={()=>act(()=>sim.release(slot))}>Release selected slot</button><button className="secondary" onClick={()=>{close();game?.balcony()}}>Walk to the reading balcony ↗</button>{sim.pressed&&!sim.delivered&&<button className="action" onClick={()=>act(()=>{sim.delivered=true;sim.message='Welcome packet delivered. Pip: You’ve found your feet. The whole kingdom is open.'})}>Deliver Pip’s welcome packet</button>}</>}
 {n===3&&<><Choice label="Geometry" value={sim.geometry} values={['crystal','sphere','torus']} onChange={v=>act(()=>{sim.geometry=v;game?.gpu(sim)})}/><Choice label="Material" value={sim.material} values={['violet','copper','mint']} onChange={v=>act(()=>{sim.material=v;game?.gpu(sim)})}/><Choice label="Lighting" value={sim.lighting} values={['warm','cool','dramatic']} onChange={v=>act(()=>{sim.lighting=v;game?.gpu(sim)})}/><div className="log"><b>LIVE OBJECT</b><p>{sim.geometry} · {sim.material} · {sim.lighting} light</p><p>Close this panel to orbit your finished object and explore the color garden.</p></div></>}
 {n===4&&<><Choice label="Destination" value={dest} values={['RAM Library','CPU Core Cities','GPU Rendering District']} onChange={setDest}/><button className="action" disabled={!!sim.packet&&!sim.packet.done} onClick={()=>act(()=>sim.send(dest))}>Send packet →</button><div className="hop-list">{(sim.packet?.hops||['Source NIC','Router A','Switch B',dest]).map((h,i)=><div key={i} className={sim.packet&&i<=sim.packet.hop?'active':''}><span>{i}</span>{h}{sim.packet?.hop===i&&<b>{sim.packet.done?'DELIVERED':'CARGO HERE'}</b>}</div>)}</div></>}
 {n===5&&<><label className="field">Record ID<input type="number" value={record} onChange={e=>setRecord(e.target.value)} min="0" step="1"/></label><button className="action" disabled={!!sim.lookup&&!sim.lookup.done} onClick={()=>act(()=>sim.search(Number(record)))}>Run indexed lookup</button><div className="record-grid">{sim.records.map(r=><span key={r.id} className={!sim.lookup||sim.lookup.candidates.includes(r.id)?'active':''}>{r.id}</span>)}</div><div className="log">{sim.lookup?.steps.map((s,i)=><p key={i}>{i+1}. {s}</p>)}{sim.lookup?.result&&<b>{sim.lookup.result}</b>}</div><button className="secondary" onClick={()=>{close();game?.vault()}}>Descend into the record vault ↓</button></>}
 {n===6&&<><div className="core-grid">{[0,1,2].map(i=><div key={i}><small>NODE {'ABC'[i]}</small><b>{sim.pods.find(p=>p.node===i)?.id||'Capacity free'}</b><span>{sim.pods.find(p=>p.node===i)?.ready?'Ready':sim.pods.some(p=>p.node===i)?'Not Ready':'Eligible'}</span></div>)}</div><button className="action" disabled={sim.failureAge>=0} onClick={()=>act(()=>sim.fail())}>Simulate pod failure</button><div className="log">{sim.clusterLog.map((s,i)=><p key={i}>{s}</p>)}</div><button className="secondary" onClick={()=>{close();game?.lift()}}>Ride the service lift ↕</button></>}
 {n===7&&<><div className="two-fields"><label className="field">Partition key<input value={eventKey} maxLength={30} onChange={e=>setEventKey(e.target.value)}/></label><label className="field">Event<input value={value} maxLength={50} onChange={e=>setValue(e.target.value)}/></label></div><button className="action" onClick={()=>act(()=>sim.publish(eventKey,value))}>Publish event +</button><div className="partitions">{sim.partitions.map((events,p)=><div key={p}><b>P{p}</b><span>{events.map((e,i)=><em key={e.id} title={e.key+': '+e.value}>{i}<small>#{e.id}</small></em>)}</span></div>)}</div><Choice label="Consumer group" value={group} values={['garden','archive']} onChange={setGroup}/><Choice label="Partition" value={partition} values={['0','1','2']} onChange={setPartition}/><div className="two-fields"><button className="action" onClick={()=>act(()=>sim.consume(group,+partition))}>Advance offset →</button><button className="secondary" onClick={()=>act(()=>sim.replay(group,+partition))}>Replay from 0 ↶</button></div><div className="log">{Object.entries(sim.offsets).map(([g,o])=><p key={g}><b>{g}</b> · P0:{o[0]} / P1:{o[1]} / P2:{o[2]}</p>)}</div></>}
 {n>=0&&<><output className="machine-output" aria-live="polite">{sim.message}</output><details className="simplification"><summary>How this model is simplified</summary><p>{notes[n]}</p></details></>}
 {panel==='projects'&&projects.map((p,i)=><article className="project" key={p.name}><div className="eyebrow">0{i+1} / {p.kind}</div><h3>{p.name}</h3><p>{p.description}</p><small>{p.stack}</small><button className="action" onClick={()=>{close();game?.enterProject(i)}}>Enter this building →</button></article>)}
 {panel==='info'&&<><div className="profile"><CpuMark/><h3>{portfolio.name}</h3><p>{portfolio.role}</p><small>PROFILE AWAITS YOUR DETAILS</small></div><Tabs defaultValue="profile"><TabsList><TabsTrigger value="profile">Profile</TabsTrigger><TabsTrigger value="experience">Experience</TabsTrigger><TabsTrigger value="system">This system</TabsTrigger></TabsList><TabsContent value="profile"><p>{portfolio.summary}</p><p>{portfolio.contact}</p></TabsContent><TabsContent value="experience"><h3>Experience</h3><p>{portfolio.experience}</p><h3>Education</h3><p>{portfolio.education}</p></TabsContent><TabsContent value="system"><p>Single-player · local gravity · seven simulated districts.</p><p>Built with TypeScript, React, and Three.js. No external services are called by the machines. Simulation state lasts for this session.</p><p>Keyboard: WASD / arrows to walk, Shift to run, E to interact. Drag to orbit, scroll to zoom. Map icons offer optional fast travel.</p></TabsContent></Tabs><button className="secondary" onClick={()=>{const text=`${portfolio.name}\n${portfolio.role}\n\n${portfolio.summary}\n\nExperience\n${portfolio.experience}\n\nEducation\n${portfolio.education}\n\n${portfolio.contact}\n\nTemplate profile — replace placeholder details before sharing.`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='system-information-resume-template.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}}>Download résumé template ↓</button></>}
 </SheetContent></Sheet>
}
function CpuMark(){return <span className="profile-mark">▦</span>}
