export type Job={id:number,core:number|null,remaining:number,status:'queued'|'running'|'complete'};
export class KingdomSimulation {
 jobs:Job[]=[];slots:(string|null)[]=Array(12).fill(null);nextJob=1;nextData=1;clock=0;
 geometry='crystal';material='violet';lighting='warm';
 packet:{destination:string,hops:string[],hop:number,elapsed:number,done:boolean}|null=null;
 lookup:{key:number,candidates:number[],steps:string[],elapsed:number,done:boolean,result:string|null}|null=null;
 records=Array.from({length:16},(_,i)=>({id:(i+1)*10,name:['Boot manifest','Copper garden','Pip’s workshop','Clock schedule','Memory map','Library catalog','Shader recipe','Render frame','Router table','Packet receipt','Pod manifest','Node capacity','Event ledger','Consumer offset','Project index','System profile'][i]}));
 pods=[{id:'pod-a',node:0,ready:true},{id:'pod-b',node:1,ready:true}];failureAge=-1;routed='pod-a';clusterLog=['Service → pod-a (Ready)','Desired replicas: 2 · eligible nodes: A, B, C'];replacement=1;
 partitions:{id:number,key:string,value:string}[][]=[[],[],[]];offsets:Record<string,number[]>={garden:[0,0,0],archive:[0,0,0]};nextEvent=1;eventLog='Publish a retained event to begin.';
 message='Pip: Use WASD to walk, drag to look, then press E beside my Packet Press.';pressed=false;delivered=false;
 submit(){if(this.jobs.filter(j=>j.status!=='complete').length>=9)return this.message='Queue full: let a core finish first.';this.jobs.push({id:this.nextJob++,core:null,remaining:3,status:'queued'});return this.message='Job joined the FIFO ready queue.'}
 allocate(){const i=this.slots.indexOf(null);if(i<0)return this.message='All 12 slots are occupied. Release one first.';this.slots[i]='thought-'+this.nextData++;return this.message=`Allocated ${this.slots[i]} at address 0x${(i*16).toString(16).padStart(2,'0')}.`}
 release(i:number){if(!Number.isInteger(i)||i<0||i>=12)throw Error('Invalid memory slot');const old=this.slots[i];this.slots[i]=null;return this.message=old?`Released ${old}. Address 0x${(i*16).toString(16).padStart(2,'0')} is free.`:'This slot is already free.'}
 send(destination:string){if(!['RAM Library','CPU Core Cities','GPU Rendering District'].includes(destination))throw Error('Unknown destination');this.packet={destination,hops:['Source NIC','Router A','Switch B',destination],hop:0,elapsed:0,done:false};return this.message='Packet dispatched. Follow its glowing cargo through the labeled hops.'}
 search(key:number){if(!Number.isInteger(key))throw Error('Record ID must be an integer');this.lookup={key,candidates:this.records.map(r=>r.id),steps:['Root index: 16 sorted keys'],elapsed:0,done:false,result:null};return this.message=`Searching the index for record ${key}…`}
 fail(){if(this.failureAge>=0)return this.message='Replacement is already being scheduled.';const victim=this.pods.find(p=>p.ready);if(!victim)return;victim.ready=false;this.routed=this.pods.find(p=>p.ready)!.id;this.failureAge=0;this.clusterLog=[`${victim.id} failed on node ${'ABC'[victim.node]}`,`Readiness removes failed endpoint → ${this.routed}`, 'Controller observes 1/2 Ready replicas'];return this.message='Traffic now reaches the ready replica. Replacement pending.'}
 publish(key:string,value:string){if(!key.trim()||!value.trim())throw Error('Add a key and event value');if(this.partitions.flat().length>=90)return this.message='Demo log capacity reached (90 events). Retained events remain replayable.';const p=[...key].reduce((a,c)=>a+c.charCodeAt(0),0)%3;const event={id:this.nextEvent++,key,value};this.partitions[p].push(event);this.eventLog=`Event ${event.id} appended to P${p} at offset ${this.partitions[p].length-1}.`;return this.message=this.eventLog}
 consume(group:string,p:number){if(!this.offsets[group]||p<0||p>2||!Number.isInteger(p))throw Error('Invalid consumer');const o=this.offsets[group][p],e=this.partitions[p][o];if(!e)return this.message=`${group} is caught up on P${p}.`;this.offsets[group][p]++;return this.message=this.eventLog=`${group} read #${e.id} (${e.value}) from P${p}:${o}; next offset ${o+1}.`}
 replay(group:string,p:number){if(!this.offsets[group]||p<0||p>2||!Number.isInteger(p))throw Error('Invalid consumer');this.offsets[group][p]=0;return this.message=this.eventLog=`${group} seeked P${p} to 0. Advance to replay retained events; the other group is unchanged.`}
 tick(dt:number){this.clock+=dt;
 for(const j of this.jobs)if(j.status==='running'){j.remaining-=dt;if(j.remaining<=0){j.status='complete';this.message=`Job #${j.id} finished on core ${j.core!+1}.`}}
 for(let c=0;c<3;c++)if(!this.jobs.some(j=>j.status==='running'&&j.core===c)){const j=this.jobs.find(j=>j.status==='queued');if(j&&this.clock-(Math.floor(this.clock))<dt){j.status='running';j.core=c}}
 if(this.jobs.length>30)this.jobs=this.jobs.filter(j=>j.status!=='complete').concat(this.jobs.filter(j=>j.status==='complete').slice(-12));
 if(this.packet&&!this.packet.done){this.packet.elapsed+=dt;if(this.packet.elapsed>=1.6){this.packet.elapsed=0;this.packet.hop++;if(this.packet.hop===3){this.packet.done=true;this.message=`Packet delivered to ${this.packet.destination} in 3 hops.`}}}
 const q=this.lookup;if(q&&!q.done){q.elapsed+=dt;if(q.elapsed>=1){q.elapsed=0;const mid=Math.floor(q.candidates.length/2),id=q.candidates[mid];if(id===q.key){q.candidates=[id];q.result=this.records.find(r=>r.id===id)!.name;q.done=true;q.steps.push(`Leaf → ${id}: ${q.result}`);this.message=`Record found: ${q.result}.`}else{q.candidates=q.key<id?q.candidates.slice(0,mid):q.candidates.slice(mid+1);q.steps.push(`${q.key<id?'Left':'Right'} branch → ${q.candidates.length} candidate keys`);if(!q.candidates.length){q.done=true;q.steps.push('No matching record');this.message='No record matches this ID.'}}}}
 if(this.failureAge>=0){this.failureAge+=dt;if(this.failureAge>=2&&this.clusterLog.length===3){const occupied=this.pods.filter(p=>p.ready).map(p=>p.node);const node=[0,1,2].find(n=>!occupied.includes(n))!;this.pods=this.pods.filter(p=>p.ready);this.pods.push({id:'pod-r'+this.replacement++,node,ready:false});this.clusterLog.push(`Scheduler → node ${'ABC'[node]} (free capacity, eligible)`)}if(this.failureAge>=4){this.pods.forEach(p=>p.ready=true);this.clusterLog.push('Readiness passed → 2/2 Ready replicas');this.failureAge=-1;this.message='Replacement Ready. Desired replica count restored.'}}
 }
 snapshot(){return {jobs:this.jobs,slots:this.slots,packet:this.packet,lookup:this.lookup,pods:this.pods,routed:this.routed,partitions:this.partitions,offsets:this.offsets,message:this.message}}
}
