const fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib');
const {values:options}=require('node:util').parseArgs({options:{label:{type:'string',default:'baseline'},url:{type:'string',default:'http://127.0.0.1:3001/'},mobile:{type:'boolean'},quick:{type:'boolean'},cpu:{type:'boolean'},production:{type:'boolean'}}});
const packageRoot=(process.env.PATH??'').split(path.delimiter).map(directory=>path.resolve(directory,'..','playwright')).find(directory=>fs.existsSync(path.join(directory,'package.json')));
const {chromium}=require(packageRoot??'playwright'),output=path.resolve('outputs/performance/'+options.label+(options.mobile?'-mobile':'-desktop'));fs.mkdirSync(output,{recursive:true});
async function main(){
 const channel=fs.existsSync('C:/Program Files/Google/Chrome/Application/chrome.exe')?'chrome':'msedge',browser=await chromium.launch({channel,headless:true,args:['--enable-precise-memory-info']}),page=await browser.newPage({viewport:options.mobile?{width:390,height:844}:{width:1440,height:960},deviceScaleFactor:2,isMobile:!!options.mobile,hasTouch:!!options.mobile}),client=await page.context().newCDPSession(page),events=[],requests=new Map(),samples=[];
 page.setDefaultTimeout(60000);page.on('pageerror',error=>events.push({event:'pageerror',message:error.message}));page.on('crash',()=>events.push({event:'crash'}));page.on('framenavigated',frame=>{if(frame===page.mainFrame())events.push({event:'navigation',url:frame.url()})});page.on('console',message=>{if(/context lost|out of memory|Shader Error|too many active webgl/i.test(message.text()))events.push({event:'console',message:message.text()})});
 await client.send('Network.enable');await client.send('Network.setCacheDisabled',{cacheDisabled:true});client.on('Network.responseReceived',event=>requests.set(event.requestId,{url:event.response.url,type:event.type,status:event.response.status,mime:event.response.mimeType,decoded:Number(event.response.headers['Content-Length']??event.response.headers['content-length']??0),encoded:0}));client.on('Network.loadingFinished',event=>{const request=requests.get(event.requestId);if(request)request.encoded=event.encodedDataLength});
 await page.addInitScript(()=>{
  localStorage.setItem('living-computer-kingdom:v1',JSON.stringify({version:1,settings:{muted:true,quality:'auto',cameraMode:'far',worldLighting:'day'}}));Object.defineProperty(navigator,'geolocation',{configurable:true,value:{getCurrentPosition(_success,error){error?.({code:1})}}});
  globalThis.__profileDocument=crypto.randomUUID();globalThis.__profileLost=0;globalThis.__profileReady=null;globalThis.__profileLongTasks=[];globalThis.__profileLcp=[];globalThis.__profileFrames=[];
  document.addEventListener('webglcontextlost',()=>globalThis.__profileLost++,true);
  new PerformanceObserver(list=>globalThis.__profileLongTasks.push(...list.getEntries().map(entry=>({start:entry.startTime,duration:entry.duration})))).observe({type:'longtask',buffered:true});
  new PerformanceObserver(list=>globalThis.__profileLcp.push(...list.getEntries().map(entry=>({time:entry.startTime,size:entry.size})))).observe({type:'largest-contentful-paint',buffered:true});
  new MutationObserver(()=>{if(globalThis.__profileReady===null&&document.querySelector('main.kingdom')?.getAttribute('data-ready')==='true')globalThis.__profileReady=performance.now()}).observe(document,{subtree:true,attributes:true,attributeFilter:['data-ready']});
 });
 if(options.cpu){await client.send('Profiler.enable');await client.send('Profiler.start')}
 try{
  console.log('WORLD_PROFILE_START '+JSON.stringify({label:options.label,channel,mobile:!!options.mobile}));await page.goto(options.url,{waitUntil:'domcontentloaded',timeout:240000});
  await page.waitForFunction(()=>{const main=document.querySelector('main.kingdom');if(main?.getAttribute('data-ready')!=='true')return false;let fiber=main[Object.keys(main).find(key=>key.startsWith('__reactFiber'))];while(fiber){for(let hook=fiber.memoizedState;hook;hook=hook.next){const world=hook.memoizedState?.current;if(world?.scene&&world?.renderer){globalThis.__profileWorld=world;return true}}fiber=fiber.return}return false},null,{timeout:240000});
    const hot=[];
    if(options.cpu){const cpu=await client.send('Profiler.stop');fs.writeFileSync(path.join(output,'startup.cpuprofile'),JSON.stringify(cpu.profile));const functions=new Map();for(const node of cpu.profile.nodes){const frame=node.callFrame,key=frame.functionName+' '+frame.url;functions.set(node.id,key)}const times=new Map();cpu.profile.samples?.forEach((id,index)=>{const key=functions.get(id);times.set(key,(times.get(key)??0)+(cpu.profile.timeDeltas[index]??0))});hot.push(...[...times].sort((first,second)=>second[1]-first[1]).slice(0,25).map(([name,microseconds])=>({name,milliseconds:microseconds/1000})))}
  async function snapshot(label){
   await page.evaluate(()=>new Promise(resolve=>{let frames=0;const next=()=>{if(++frames===2)resolve();else requestAnimationFrame(next)};requestAnimationFrame(next)}));
   await client.send('HeapProfiler.collectGarbage');
   const value=await page.evaluate(()=>{
    const world=globalThis.__profileWorld,geometry=new Set(),materials=new Set(),textures=new Set(),buffers=new Set(),owners={},textureDetails=[];let objects=0,meshes=0,shadowCasters=0,lights=0,shadowLights=0,geometryBytes=0,textureBytes=0,instances=0,skinned=0;
    function addBuffer(array){if(array&&!buffers.has(array.buffer)){buffers.add(array.buffer);geometryBytes+=array.buffer.byteLength}}
    world.scene.traverse(object=>{
     objects++;if(object.isLight){lights++;if(object.castShadow)shadowLights++}if(!object.geometry)return;meshes++;if(object.castShadow)shadowCasters++;if(object.isSkinnedMesh)skinned++;if(object.isInstancedMesh){instances+=object.count;addBuffer(object.instanceMatrix.array);addBuffer(object.instanceColor?.array)}
     let owner=object;while(owner.parent&&owner.parent!==world.scene)owner=owner.parent;const entry=owners[owner.name||owner.type]??={objects:0,geometryBytes:0};entry.objects++;
     if(!geometry.has(object.geometry)){geometry.add(object.geometry);const before=geometryBytes;for(const attribute of Object.values(object.geometry.attributes))addBuffer(attribute.array??attribute.data?.array);addBuffer(object.geometry.index?.array);entry.geometryBytes+=geometryBytes-before}
     for(const material of Array.isArray(object.material)?object.material:[object.material]){if(!material||materials.has(material))continue;materials.add(material);const values=[...Object.values(material),...Object.values(material.uniforms??{}).map(uniform=>uniform.value)];for(const texture of values)if(texture?.isTexture&&!textures.has(texture)){textures.add(texture);const image=texture.image??texture.source?.data;if(image?.width&&image?.height){const estimate=image.width*image.height*4*(texture.generateMipmaps?4/3:1);textureBytes+=estimate;textureDetails.push({name:texture.name,width:image.width,height:image.height,estimatedBytes:Math.round(estimate)})}}}
    });
    const context=world.renderer.getContext(),debug=context.getExtension('WEBGL_debug_renderer_info');
    return {document:globalThis.__profileDocument,contextLost:globalThis.__profileLost,readyMs:globalThis.__profileReady,paints:performance.getEntriesByType('paint').map(entry=>({name:entry.name,time:entry.startTime})),lcp:globalThis.__profileLcp.at(-1),heap:performance.memory?.usedJSHeapSize,objects,meshes,materials:materials.size,textures:textures.size,geometryCount:geometry.size,geometryBytes,estimatedTextureBytes:Math.round(textureBytes),largestTextures:textureDetails.sort((first,second)=>second.estimatedBytes-first.estimatedBytes).slice(0,12),shadowCasters,lights,shadowLights,skinned,instances,owners,renderer:{geometries:world.renderer.info.memory.geometries,textures:world.renderer.info.memory.textures,programs:world.renderer.info.programs.length,draws:world.renderer.info.render.calls,triangles:world.renderer.info.render.triangles,pixelRatio:world.renderer.getPixelRatio(),width:world.renderer.domElement.width,height:world.renderer.domElement.height,gpu:debug?context.getParameter(debug.UNMASKED_RENDERER_WEBGL):null},streaming:world.transport?.streaming?.snapshot?.()??null,longTasks:globalThis.__profileLongTasks};
   });samples.push({label,...value});console.log('WORLD_SAMPLE '+JSON.stringify({label,readyMs:value.readyMs,heapMiB:value.heap/1048576,objects:value.objects,geometryMiB:value.geometryBytes/1048576,textureMiB:value.estimatedTextureBytes/1048576,draws:value.renderer.draws,triangles:value.renderer.triangles,streaming:value.streaming}));return value;
  }
  await snapshot('ready');const initialRequests=[...requests.values()].filter(request=>/^https?:/.test(request.url));
    await page.evaluate(()=>Promise.allSettled([globalThis.__profileWorld.dog.ready,globalThis.__profileWorld.angel.ready,globalThis.__profileWorld.goldMonument.ready,globalThis.__profileWorld.resumeBooks.ready]));
    await page.waitForFunction(()=>!globalThis.__profileWorld.city.streaming||globalThis.__profileWorld.city.streaming().loading===0,null,{timeout:120000});
    await page.evaluate(()=>new Promise(resolve=>{let frames=0;function next(){if(++frames>=30)resolve();else requestAnimationFrame(next)}requestAnimationFrame(next)}));
  const frameTimes=await page.evaluate(()=>new Promise(resolve=>{const times=[];let previous=performance.now();function next(now){times.push(now-previous);previous=now;if(times.length>=120)resolve(times);else requestAnimationFrame(next)}requestAnimationFrame(next)}));
  await snapshot('settled');
  await page.getByRole('button',{name:'View controls',exact:true}).click();for(const mode of ['Close camera','First person camera','Far camera'])await page.getByRole('button',{name:mode,exact:true}).click();await page.keyboard.press('Escape');
  const bounds=await page.locator('.world canvas').boundingBox();await page.mouse.move(bounds.width*.5,bounds.height*.5);await page.mouse.down();await page.mouse.move(bounds.width*.85,bounds.height*.65,{steps:16});await page.mouse.move(bounds.width*.15,bounds.height*.4,{steps:24});await page.mouse.up();await snapshot('camera-rotation');
  if(!options.quick)for(const stop of [1,3,0,1,3,0]){
   await page.evaluate(stop=>globalThis.__profileWorld.goSharedPlanet(stop),stop);
   await page.waitForFunction(stop=>{const world=globalThis.__profileWorld;return !world.transport?.streaming||world.transport.streaming.ready?.(stop)!==false},stop,{timeout:120000});
   await snapshot('planet-'+stop);
  }
    if(!options.quick){await page.waitForFunction(()=>!globalThis.__profileWorld.transport.streaming||globalThis.__profileWorld.transport.streaming.snapshot().resident===0,null,{timeout:45000,polling:500});await snapshot('returned-and-unloaded')}
  await page.evaluate(()=>globalThis.__profileWorld.goCapital('plaza'));await page.screenshot({path:path.join(output,'plaza.png')});
    const mean=frameTimes.reduce((sum,time)=>sum+time,0)/frameTimes.length,sorted=[...frameTimes].sort((first,second)=>first-second),report={label:options.label,channel,mobile:!!options.mobile,url:options.url,environment:options.production?'local production build, same browser and machine':'local development build',samples,frame:{count:frameTimes.length,mean,p95:sorted[Math.floor(sorted.length*.95)],fps:1000/mean},initialNetwork:{requests:initialRequests.length,encodedBytes:initialRequests.reduce((sum,request)=>sum+request.encoded,0),scriptBytes:initialRequests.filter(request=>request.type==='Script').reduce((sum,request)=>sum+request.encoded,0),models:initialRequests.filter(request=>/\.glb(?:\?|$)/.test(request.url)),largest:initialRequests.sort((first,second)=>second.encoded-first.encoded).slice(0,20)},cpu:hot,events};
  const assets=[];for(const directory of ['public/assets']){const walk=folder=>{for(const entry of fs.readdirSync(folder,{withFileTypes:true})){const name=path.join(folder,entry.name);if(entry.isDirectory()){if(!name.includes('friends-pc'))walk(name)}else if(/\.(glb|png|jpe?g|webp|avif|ktx2|mp3|ogg|wav)$/i.test(name)){const data=fs.readFileSync(name);assets.push({name,bytes:data.length,gzipBytes:zlib.gzipSync(data).length})}}};walk(directory)}report.assetInventory=assets.sort((first,second)=>second.bytes-first.bytes);
  fs.writeFileSync(path.join(output,'metrics.json'),JSON.stringify(report,null,2)+'\n');console.log('WORLD_PROFILE_DONE '+JSON.stringify({frame:report.frame,network:report.initialNetwork.encodedBytes,scriptBytes:report.initialNetwork.scriptBytes,events}));
 }finally{await browser.close()}
}
main().catch(error=>{console.error(error);process.exitCode=1});
